sr_action_interrupt = [
    {
        action_id: "action_block",
        action_class: "button button_action", 
        icon: "images/action_block.png",
        btn_desc: "<b>Block</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Block",
        book_src: "Core Rulebook, p.168",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "A character may choose to use her own unarmed combat skill to block incoming melee attacks as an Interrupt Action (see Defending in Combat, p. 188). By decreasing her Initiative Score, the defending character can add her Unarmed Combat skill to their defense test. This is a one-time add, unlike going on Full Defense (below) which lasts for an entire Combat Turn."
    },
    {
        action_id: "action_dodge",
        action_class: "button button_action", 
        icon: "images/action_dodge.png",
        btn_desc: "<b>Dodge</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Dodge",
        book_src: "Core Rulebook, p.168",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "A character may choose to use her own skill to dodge incoming attacks as an Interrupt Action (see Defending in Combat, p. 188). By decreasing her Initiative Score, the defending character can add her Gymnastics skill to the defense test. This is a one-time add, unlike going on Full Defense (below) which lasts for an entire Combat Turn."
    },
    {
        action_id: "action_hitthedirt",
        action_class: "button button_action", 
        icon: "images/action_dropprone.png",
        btn_desc: "<b>Hit The Dirt</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Hit The Dirt",
        book_src: "Core Rulebook, p.168",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "A character who has already used their Free Action may choose to drop prone when caught by suppressive fire using this action (see Suppressive Fire, p. 179). The defending character doesn't need to make the Reaction + Edge test but is considered prone on their next Action Phase. If the suppressive fire continues, the defending character needs to use a Stand Up Simple Action to get back up, risking getting shot, or fight from the ground. If the suppressive fire has stopped the prone character still needs to use a Stand Up Simple Action to get back up."
    },
    {
        action_id: "action_intercept",
        action_class: "button button_action", 
        icon: "images/action_intercept.png",
        btn_desc: "<b>Intercept</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Intercept",
        book_src: "Core Rulebook, p.168",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "A character may take an Interrupt Action to intercept an opponent who attempts to move past him (within 1 + Reach meter(s)) or break out of melee combat (see Interception, p. 194). The Intercept Action allows a character to make a melee attack out of turn. If the character does not have enough Initiative Score left that Action Phase he cannot intercept."
    },
    {
        action_id: "action_parry",
        action_class: "button button_action", 
        icon: "images/action_parry.png",
        btn_desc: "<b>Parry</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Parry",
        book_src: "Core Rulebook, p.168",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "A character may choose to use his own melee weapon skill to deflect incoming melee attacks as an Interrupt Action (see Defending in Combat, p. 188). By decreasing his Initiative Score, the defending character can add his melee weapon skill to their defense test. This is a one-time add, unlike going on Full Defense (below), which lasts for an entire Combat Turn. Bonus die, such as die from a relevant weapon foci, can be added to this test."
    },
    {
        action_id: "action_fulldefense",
        action_class: "button button_action", 
        icon: "images/action_fulldefense.png",
        btn_desc: "<b>Full Defense</b><br><br><i>Interrupt Action</i><br><i><b>-10 Initiative Score</b></i>",
        title: "Full Defense",
        book_src: "Core Rulebook, p.168",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-10 Initiative Score</i>",
        action_detail2: "",
        description: "A character may choose to focus on deliberately avoiding incoming attacks as an Interrupt Action (see Defending in Combat, p. 188). This action adds the character's Willpower to their Defense tests for the entire Combat Turn. Full Defense actions may be taken at any time, even before the character's Action Phase as an Interrupt Action, as long as the character is not surprised. Characters may only go on Full Defense if they have enough Initiative Score left in that Combat Turn. The bonus gained in this manner is kept until the end of the Combat Turn so a character can choose to fight defensively early in the round by decreasing her Initiative Score to increase her defense. This bonus is also cumulative with other Interrupt Actions."
    },
    {
        action_id: "matrix_fmd",
        action_class: "button button_matrix", 
        icon: "images/matrix_fmd.png",
        btn_desc: "<b>Full Matrix Defense</b><br><br><i>Interrupt Action</i><br><i><u>Matrix Action</u></i><br><i><b>-10 Initiative Score</b></i>",
        title: "Full Matrix Defense",
        book_src: "Core Rulebook, p.240",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-10 Initiative Score</i> <br><br><u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> Owner <br> <b>Test:</b> none (Firewall action)",
        description: "This allows you to defend against Attack actions, and may be taken at any time. Whenever you make a defense test against a Matrix Action, add your Willpower to the dice pool (or add it again if it's already in there). When you take this action, your Initiative Score is reduced by 10, but the effects last for the rest of the Combat Turn."
    },
    {
        action_id: "action_counterstrike",
        action_class: "button button_martial", 
        icon: "images/action_counterstrike.png",
        btn_desc: "<b>Counterstrike</b><br><br><i>Interrupt Action</i><br><i><u>Martial Art Required</u></i><br><i><b>-7 Initiative Score</b></i>",
        title: "Counterstrike",
        book_src: "Run & Gun, p.124",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i><u>Unarmed Combat Only</u></i><br><br> <i>-7 Initiative Score</i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "Counterstrike allows the character to leverage the opponent's force into an advantage, allowing the character to make a quick strike back. In place of the standard Defense Test, the character makes an Unarmed Combat + Reaction [Physical] Test against the opponent's standard Attack Test. If the defender achieves more hits than the attacker, the defender successfully avoided the attacker's strike while returning and landing a strike of their own. The defender's counterstrike attack has a Damage Value equal to the defending character's standard Unarmed DV + net hits. The damage is resisted by a standard Damage Resistance Test. If the defender does not achieve more hits, then he must make a Damage Resistance Test against the damage of the attacker's strike as normal."
    },
    {
        action_id: "action_diveforcover",
        action_class: "button button_action", 
        icon: "images/action_diveforcover.png",
        btn_desc: "<b>Dive For Cover</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Dive For Cover",
        book_src: "Run & Gun, p.124",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "Sometimes you don't want to just sprawl out face-flat down on the ground to get below the incoming stints of spray-and-pray Suppressive Fire. Being face down behind some cover so you can get to your feet without taking some rounds is a much better option than getting perforated. This action allows a character to go prone behind nearby cover. A character that is within the area of a Suppressive Fire Attack can choose to take an Interrupt Action and reduce their Initiative Score by 5 and Drop Prone behind any cover within 4 meters."
    },
    {
        action_id: "action_reversal",
        action_class: "button button_martial", 
        icon: "images/action_reversal.png",
        btn_desc: "<b>Reversal</b><br><br><i>Interrupt Action</i><br><i><u>Martial Art Required</u></i><br><i><b>-7 Initiative Score</b></i>",
        title: "Reversal",
        book_src: "Run & Gun, p.124",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i><u>Unarmed Combat Only</u></i> <br><br> <i>-7 Initiative Score</i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "When a character finds himself stuck in a headlock or some other form of Clinch or Grapple Action and does not have the Superior Position melee modifier, he has two options: Escape or Reversal. With a Reversal, the character makes an Unarmed Attack Test with a threshold equal to the opponent's hits from their Clinch or Subduing Action. If successful, the character and opponent are still engaged in a Clinch or Subduing Action, but the roles become reversed, giving the character the Superior Position advantage and if reversing a Grapple, the character can then attempt a Subduing Action on his next Action Phase."
    },
    {
        action_id: "action_rightbackatya",
        action_class: "button button_action", 
        icon: "images/action_rightbackatya.png",
        btn_desc: "<b>Right Back At Ya!</b><br><br><i>Interrupt Action</i><br><i><b>-10 Initiative Score, Agility Test, Throwing Weapon Test</b></i>",
        title: "Right Back At Ya!",
        book_src: "Run & Gun, p.124",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-10 Initiative Score, Agility Test, Throwing Weapons Test</i>",
        action_detail2: "",
        description: "Crazy is as crazy does, and this is what crazy does. This action allows a character to return an incoming grenade by either intercepting its course in flight or scooping it up off the ground and tossing it back. This action is greatly affected by the type of trigger on the grenade. With a basic attack and built-in timer trigger, the acting character needs enough Movement remaining to reach the grenade or get into its path. If a gamemaster is meticulous about distances in combat and wants to be nasty, she can make the character decide to attempt this before knowing if they have enough Movement. If the character lacks the necessary Movement, they simply move closer to the grenade and get themselves some extra damage when the drek hits the fan. After sufficient Movement is determined, the character needs to make an Agility (2) Test to successfully pick up or intercept the grenade. After that successful test, the character makes a Throwing Weapons Attack Test with a –2 dice penalty due to all the other activity involved in this action to throw the grenade.<br><br>A grenade with a wireless trigger acts in essentially the same way; the character just has to hope they can act quickly enough to counter the grenade before it is wirelessly triggered.<br><br>When a grenade is armed with a motion sensor trigger, this action turns ugly. The character needs sufficient Movement as before, but instead of being able to send the grenade back, they simply end up at zero distance when the grenade explodes. They can however, choose to intercept the grenade anywhere in its path, though they won't know the effect until after the big boom."
    },
    {
        action_id: "action_divegrenade",
        action_class: "button button_action", 
        icon: "images/action_divegrenade.png",
        btn_desc: "<b>Run For Your Life/Dive On The Grenade</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Run For Your Life/Dive On The Grenade",
        book_src: "Run & Gun, p.125",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "There are few things as frightening as the distinctive sound of a grenade bouncing into your vicinity or watching a swirling ball of mana headed your way and set to go boom. By the time you realize a whole lot of trouble is on the way, there are very few options available. This action covers two of those options. There is a third, far more dangerous, option for incoming grenades covered by the Right Back At Ya! Action.<br><br>Immediately after a Throwing Weapons Attack or Area-Effect Indirect Combat Spell Spellcasting Test, a character can make an immediate Interrupt Action to flee. The character chooses a direction to move and can use any amount of available Movement to move away from the incoming attack. (Note that the gamemaster is not obligated to determine or declare the final location of the attack in the case of a fleeing character. A bad bounce can still get a grenade on the character's tail.)<br><br>In the case of diving on the grenade, the character moves toward the grenade, still limited by available remaining Movement, and can choose to make a Drop Prone Free Action when reaching the grenade. The sacrifice means the character takes all the grenade damage and eliminates the blast. In the case of a gas grenade, this action cuts the effective radius in half."
    },
    {
        action_id: "action_sacrificethrow",
        action_class: "button button_martial", 
        icon: "images/action_sacrificethrow.png",
        btn_desc: "<b>Sacrifice Throw</b><br><br><i>Interrupt Action</i><br><i><u>Martial Art Required</u></i><br><i><b>-10 Initiative Score</b></i>",
        title: "Sacrifice Throw",
        book_src: "Run & Gun, p.125",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-10 Initiative Score</i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "A throw normally keeps the character standing, using their hip, leg, or shoulder to leverage the opponent into being thrown. The Sacrifice Throw technique uses the whole character's body as counterweight for the throw. At the end both the character and opponent are Prone. Add the character's Strength and Body to the net hits of the unarmed attack to determine if it exceeds the opponent's Physical Limit. If successful, the opponent can then be thrown up to a number of meters equal to 1 plus the net hits scored on the test. The maximum distance that a character can throw an opponent is the difference in the character's Strength minus the opponent's Body in meters. If this distance value is less than 0, then the maximum distance is 0, meaning less than one meter away from the character. The opponent suffers damage equal to the net successes of the test, not the distance thrown. If the initial test is successful but the throwing character did not exceed the opponent's Physical Limit, then both characters are on the ground with no damage done to either. If the attack is unsuccessful, the throwing character is Prone and takes damage equal to the number of net hits scored by the opponent minus the throwing character's Physical Limit. This may be no damage if the character succeeded in the attack, but did not exceed the opponent's Physical Limit."
    },
    {
        action_id: "action_riposte",
        action_class: "button button_martial", 
        icon: "images/action_riposte.png",
        btn_desc: "<b>Riposte</b><br><br><i>Interrupt Action</i><br><i><u>Martial Art Required</u></i><br><i><b>-7 Initiative Score</b></i>",
        title: "Riposte",
        book_src: "Run & Gun, p.125",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i><u>Armed Melee Combat Only</u></i> <br><br> <i>-7 Initiative Score</i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "Riposte allows shadowrunners to leverage an opponent's force to their advantage, giving a character the chance to make a quick strike back at an attacker with their readied weapon. In place of the standard Defense Test, the character makes a (Melee Weapon Skill) + Reaction [Accuracy] Test against the opponent's standard Attack Test. If the defender achieves more net hits than the attacker, the defender successfully avoided the attacker's strike and managed to return a strike of their own. The defender's riposte attack has a Damage Value equal to the normal DV of the weapon + net hits and is resisted by a standard Damage Resistance Test. If the defender does not achieve more hits, then he must make a Damage Resistance Test against the damage of the attacker's strike, with the damage increased by 2 due to the defender being off balance after their failed riposte."
    },
    {
        action_id: "action_protecttheprinciple",
        action_class: "button button_action", 
        icon: "images/action_protecttheprinciple.png",
        btn_desc: "<b>Protecting The Principle</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score, 1 Edge</b></i>",
        title: "Protecting The Principle",
        book_src: "Run & Gun, p.125",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score, -1 Edge</i>",
        action_detail2: "",
        description: "The character can choose to move up to 2 meters to place themselves between an attacker and a target and take the brunt of an incoming attack. There is no Defense Test (Reaction + Intuition), only Damage Resistance (Body + Armor). This action can only be performed once per Combat Turn."
    },
    {
        action_id: "action_shadowblock",
        action_class: "button button_martial", 
        icon: "images/action_shadowblock.png",
        btn_desc: "<b>Shadow Block</b><br><br><i>Interrupt Action</i><br><i><u>Martial Art Required</u></i><br><i><b>-5 Initiative Score</b></i>",
        title: "Shadow Block",
        book_src: "Run & Gun, p.125",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "When one character in a fight tries to use their Gymnastics skill to avoid a blow, or if they are trying to get out of the fight, an opponent close to them can attempt to interfere and make sure they take the damage coming their way. If a character is using the Dodge Interrupt Action, an opponent can use Shadow Block on that opponent. They must make a Gymnastics + Agility [Physical] Test with the threshold being the opponent's net hits from their Dodge Test. If successful, the character reduces the hits the Dodging character received on their Defense Test by the net hits they achieved on their test.<br><br>Shadow Block can also be used to counteract an Evade action. As above, the character with Shadow Block makes a Gymnastics + Agility [Physical] Test with the threshold being the opponent's net hits from their Evade Test. If successful they reduce this net hits on the test, thereby reducing the number of people the person attempting the Evade automatically passes. The Shadow Blocker can choose which person then can attack, but it has to be someone who was within five meters of the person attempting to Evade at some point in their movement."
    },
    {
        action_id: "action_subduing",
        action_class: "button button_action", 
        icon: "images/action_subduing.png",
        btn_desc: "<b>Subduing after an Opposite Touch-Only Attack</b><br><br><i>Interrupt Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Subduing",
        book_src: "Run & Gun, p.123",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A Subduing Action is grappling the opponent in either a choke hold or a joint lock that brings asphyxiation to the brain or pain to a joint or body part. The character follows the standard rules for Subduing (p. 195, SR5) and must spend a Complex Action per Action Phase to maintain the Subduing. As part of that action, they can perform any of the allowed options, and the opponent cannot take an action that requires Movement. A character can end the Subduing as a Free Action, but still be in contact with the opponent for that Action Phase. Subduing Actions can be done as an Interrupt Action (–5 Initiative Score) by a character on an opponent who has successfully completed a touch-only attack against him."
    },
    {
        action_id: "matrix_iamthefirewall",
        action_class: "button button_matrix", 
        icon: "images/matrix_iamthefirewall.png",
        btn_desc: "<b>I Am The Firewall</b><br><br><i>Interrupt Action</i><br><i><u>Matrix Action</u></i><br><i><b>-5 Initiative Score</b>",
        title: "I Am The Firewall",
        book_src: "Kill Code p.38",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i><br><br><u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Computer + Intuition [Data Processing]</p>",
        description: "<i>Instead of attacking, the hacker engages threat-highlighting software, giving allies an edge to their defenses.</i><br><br> I Am the Firewall allows the hacker to give a Defense test bonus to all allies with access to an AR feed from the user. The number of bonus dice is equal to the number of hits on a Computer + Intuition [Data Processing] Test. This bonus lasts until the beginning of the hacker's next Initiative Pass. The hacker can only share their feed with a number of users equal to or less than their Data Processing attribute.<br><br>When you take this action as an Interrupt Action, your Initiative Score is reduced by 5."
    },
    {
        action_id: "matrix_intervene",
        action_class: "button button_matrix", 
        icon: "images/matrix_intervene.png",
        btn_desc: "<b>Intervene</b><br><br><i>Interrupt Action</i><br><i><u>Matrix Action</u></i><br><i><b>-5 Initiative Score</b></i>",
        title: "Intervene",
        book_src: "Kill Code p.39",
        action_type: "<i>Interrupt Action</i>",
        action_detail1: "<i>-5 Initiative Score</i> <br><br><u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Computer + Intuition [Data Processing]",
        description: "<i>Tracing the invisible data trails between devices, you give your allies just enough warning to avoid serious harm.</i><br><br>This allows the hacker to give an immediate defense bonus to the owner of a device slaved to the hacker’s PAN. This action can be taken only if the device making the attack is wirelessly enabled and the hacker is aware of it. When you take this action, your Initiative Score is reduced by 5. Roll your Computer + Intuition [Data Processing], adding the number of hits to your ally’s Defense test. This bonus applies only to the current Defense test - it cannot be carried over to any other Combat Turn or Initiative Pass."
    }
]