sr_action_complex = [
    {
        action_id: "action_astralproj",
        action_class: "button button_action", 
        icon: "images/action_astralproj.png",
        btn_desc: "<b>Astral Projection</b><br><br><i>Complex Action</i>",
        title: "Astral Projection",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character capable of Astral Projection may shift their consciousness to the astral plane as a Complex Action (see p. 313)."
    },
    {
        action_id: "action_banishspirit",
        action_class: "button button_action", 
        icon: "images/action_banishspirit.png",
        btn_desc: "<b>Banish Spirit</b><br><br><i>Complex Action</i>",
        title: "Banish Spirit",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may enter into a Banishing contest with a spirit as a Complex Action"
    },
    {
        action_id: "action_castspell",
        action_class: "button button_action", 
        icon: "images/action_castspell.png",
        btn_desc: "<b>Cast Spell</b><br><br><i>Complex Action</i>",
        title: "Cast Spell",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may cast a spell as a Complex Action."
    },
    {
        action_id: "action_firefullauto",
        action_class: "button button_action", 
        icon: "images/action_firefullauto.png",
        btn_desc: "<b>Fire Full-Auto Weapon</b><br><br><i>Complex Action</i>",
        title: "Fire Full-Auto Weapon",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may fire a readied firearm in Full-Auto fire mode via a Complex Action (see Firearms, p. 424). If a character has one weapon in each hand, he may fire once with each weapon by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 196). Off-hand modifier applies (see Attacker Using Off-Hand Weapon, p. 178). When fired as a Complex Action, Full-Auto uses 10 bullets. Remember the effects of cumulative recoil when using these fire modes. And good fragging luck!"
    },
    {
        action_id: "action_firelongburst",
        action_class: "button button_action", 
        icon: "images/action_firelongburst.png",
        btn_desc: "<b>Fire Long Burst or Semi-Auto Burst</b><br><br><i>Complex Action</i>",
        title: "Fire Long Burst or Semi-Auto Burst",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may fire a readied firearm in Long Burst or Semi-Auto Burst via a Complex Action (see Firearms, p. 424). A character may attack multiple targets within Short or Medium range by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 196). If a character has one weapon in each hand, he may fire once with each weapon by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 167). Off-hand modifier applies (see Attacker Using Off-Hand Weapon, p. 178). Remember the effects of cumulative recoil when using these fire modes."
    },
    {
        action_id: "action_firemounted",
        action_class: "button button_action", 
        icon: "images/action_firemounted.png",
        btn_desc: "<b>Fire Mounted or Vehicle Weapon</b><br><br><i>Complex Action</i>",
        title: "Fire Mounted or Vehicle Weapon",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Fire a previously readied mounted or vehicle weapon by taking a Complex Action (see Vehicle Combat, p. 198)."
    },
    {
        action_id: "action_loadfirebow",
        action_class: "button button_action", 
        icon: "images/action_loadfirebow.png",
        btn_desc: "<b>Load and Fire Bow</b><br><br><i>Complex Action</i>",
        title: "Load and Fire Bow",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "With this action a character can load and fire a bow with a single Complex Action. The two activities can be reversed, Fire and Load Bow, if the bow had been readied using a Simple Action already."
    },
    {
        action_id: "action_suppressive",
        action_class: "button button_action", 
        icon: "images/action_suppressive.png",
        btn_desc: "<b>Suppressive Fire</b><br><br><i>Complex Action</i>",
        title: "Suppressive Fire",
        book_src: "Core Rulebook, p.179",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Suppressive fire takes a Complex Action, uses twenty rounds of ammo, and ignores recoil. Though it may appear as a “spray and pray” technique it is in fact a combination of controlled and fully automatic bursts focused over a narrow area and directed at anything that moves. A character can suppress a triangular area projecting from the shooting character outward up to a distance of his choosing, up to the maximum range of the weapon, with a width of 10 meters at its end and a height of 2 meters. Make a (Weapon Skill) + Agility [Accuracy] Test, including bonuses for smartlink, laser sight, tracer rounds, and other gamemaster-approved modifiers, and record the hits. The suppressive fire zone lasts until the end of the Combat Turn as long as the firer does not move or commit to any other action.<br><br>Anyone in the suppressive fire zone or immediately adjacent to it takes a dice pool penalty to all actions equal to the shooter's hits, unless they are completely unaware of it (a magician using astral projection, for example).<br><br>Any character who is in the suppressed area (but not behind cover or prone), or who moves into or out of the area before the end of the suppressive fire, risks catching some flying lead. That character must make a Reaction + Edge Test (+ any dice they may get as a result of choosing to use Full Defense) with a threshold equal to the hits scored by the suppressing attacker. Note that in the test, you use your full Edge rating, regardless of whether you have spent points during the session (though you do not, of course, use burned Edge points). If the test fails, the character is hit, suffering damage equal to the weapon's base Damage Value modified by any special ammunition being fired. Characters in the suppressed area who remain behind full cover or drop prone are not at risk (though they suffer the normal modifiers for being prone; see Melee Modifiers, p. 187, and Ranged Modifiers, p. 173). Characters may choose to avoid rolling and use their Free Action to go prone and avoid getting hit. If a character does not have a Free Action remaining she may use the Hit the Dirt Interrupt Action and go prone instead of getting hit. Any character who stands up or moves again before the suppressive fire stops must make a test to see if she is hit.<br><br>If multiple suppressive fire actions occur covering the same area, only the highest dice pool penalty counts against targets in or near the suppressed area, but targets must make a Reaction + Edge test against all overlapping zones, taking damage from the ones missed. Reaction + Edge Tests in this situation are subject to the diminishing pool effect of being shot by multiple attackers in a single Action Phase. After each roll apply a –1 die penalty to the defender's dice pool."
    },
    {
        action_id: "action_melee",
        action_class: "button button_action", 
        icon: "images/action_melee.png",
        btn_desc: "<b>Melee Attack</b><br><br><i>Complex Action</i>",
        title: "Melee Attack",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may make a melee attack by taking a Complex Action (see Melee Combat, p. 184). A character may also attack multiple targets within melee range by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 196)."
    },
    {
        action_id: "action_reload",
        action_class: "button button_action", 
        icon: "images/action_reload.png",
        btn_desc: "<b>Reload Firearm</b><br><br><i>Complex Action</i>",
        title: "Reload Firearm",
        book_src: "Core Rulebook, p.167",
        action_type: "",
        action_detail1: "",
        action_detail2: "",
        description: "Weapons that are belt fed (belt), break action (b), cylinder (cy), drum (d), internal magazine (m), muzzle loaders, or use a speed loader are reloaded using a Complex Action (see Reloading Weapons, p. 163)."
    },
    {
        action_id: "action_riggerjumpin",
        action_class: "button button_action", 
        icon: "images/action_riggerjumpin.png",
        btn_desc: "<b>Rigger Jump In</b><br><br><i>Complex Action</i>",
        title: "Rigger Jump In",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character with a VCR and rigger adapted vehicle may jump in to control the vehicle with a Complex Action."
    },
    {
        action_id: "action_sprint",
        action_class: "button button_action", 
        icon: "images/action_sprint.png",
        btn_desc: "<b>Sprint</b><br><br><i>Complex Action</i>",
        title: "Sprint",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Sprinting allows a character to increase his Running rate by using a Complex Action and making a Running Test (see Movement, p. 161)."
    },
    {
        action_id: "action_summon.png",
        action_class: "button button_action", 
        icon: "images/action_summon.png",
        btn_desc: "<b>Summoning</b><br><br><i>Complex Action</i>",
        title: "Summoning",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may summon a spirit to assist them with a Complex Action."
    },
    {
        action_id: "action_useskill",
        action_class: "button button_action", 
        icon: "images/action_useskill.png",
        btn_desc: "<b>Use Skill</b><br><br><i>Complex Action</i>",
        title: "Use Skill",
        book_src: "Core Rulebook, p.167",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may use an appropriate skill by taking a Complex Action (see Using Skills, p. 128)."
    },
    {
        action_id: "matrix_bruteforce",
        action_class: "button button_matrix", 
        icon: "images/matrix_bruteforce.png",
        btn_desc: "<b>Brute Force</b><br><br><i><u>Matrix Action</u></i>",
        title: "Brute Force",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> none <br> <b>Test:</b> Cybercombat + Logic [Attack] v. Willpower + Firewall",
        description: "You can use this action to mark a target without obtaining the normal permissions you need. This is the action for hackers emphasizing their Attack over their Sleaze, making it related to Hack on the Fly.<br><br>If you succeed in this action, you place one mark on it. You can have up to a maximum of three marks per icon. If you wish, you may also inflict 1 DV of Matrix damage to the target for every two full net hits, if the target can take Matrix damage, which is resisted with the target's Device Rating + Firewall.<br><br>Before rolling, you can declare that you are trying to place more than one mark. If you try for two marks in one shot, you take a –4 dice pool penalty on the attempt. If you try for three marks in a single swipe, you take a –10 dice pool penalty.<br><br>You can also use this action to hop to a grid for which you don't have legitimate access. The defense dice pool in this case is 4 dice for a local grid or 6 dice for a global grid. If you succeed, instead of putting a mark on the grid, you hop to that grid immediately. Using Brute Force to hop grids successfully doesn't alert the grid or its demiGOD the way most successful Attack actions do."
    },
    {
        action_id: "matrix_crackfile",
        action_class: "button button_matrix", 
        icon: "images/matrix_crackfile.png",
        btn_desc: "<b>Crack File</b><br><br><i><u>Matrix Action</u></i>",
        title: "Crack File",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 <br> <b>Test:</b> Hacking + Logic [Attack] v. Protection Rating x 2",
        description: "You remove the protection from a file, making it readable. This action doesn't need to be performed on a file that isn't protected, of course."
    },
    {
        action_id: "matrix_crashprogram",
        action_class: "button button_matrix", 
        icon: "images/matrix_crashprogram.png",
        btn_desc: "<b>Crash Program</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Crash Program",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 <br> <b>Test:</b> Cybercombat + Logic [Attack] v. Intuition + Firewall",
        description: "You overload part of your target's memory and scramble one of its running programs. You need to specify which program you're trying to crash; you can learn what your target is running either with a Matrix Perception action or by observing the program in action. If you succeed, the program is scrambled: it ends and cannot be restarted until the device it was running on is rebooted."
    },
    {
        action_id: "matrix_controldevice",
        action_class: "button button_matrix", 
        icon: "images/matrix_controldevice3.png",
        btn_desc: "<b>Control Device (3 marks)</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Control Device",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Variable Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> varies <br> <b>Test:</b>  (as action) [Data Processing (or special)] v. (as action) or Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall",
        description: "You perform an action through a device you control(or at least control sufficiently), using your commlink or deck like a remote control or video-game controller. The dice pool of any test you make using this action uses the rating of the appropriate skill and attribute you would use if you were performing the action normally. For example, firing a drone-mounted weapon at a target requires a Gunnery + Agility test, and using a remote underwater welder calls for a Nautical Mechanic + Logic test. All actions you take while controlling a device use either the normal limit for that action or your Data Processing rating, whichever is lower. If there is no test associated with the action you want the device to perform (such as unlocking a maglock or ejecting a clip from a pistol), you must succeed in an Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall test to perform the action. <br><br> You can use this action to control multiple devices at once. If you are the owner of all devices being commanded and they are all being commanded to do exactly the same thing, taking this action costs nothing extra. Otherwise, you must split your dice pool into a number of groups equal to the number of devices you want to control with a single action. <br><br> The type of action this is (i.e., Free, Simple, Standard, and Complex) is the same as the type of action attempted with the device, and it requires 1 mark for Free Actions, 2 marks for Simple Actions, and 3 marks for Standard or Complex Actions. <br><br> This action is a Sleaze action whenever you use your Sleaze as a limit in the test, which incurs the same risk of Overwatch Score and consequences of failure as all Sleaze actions."
    },
    {
        action_id: "matrix_dataspike",
        action_class: "button button_matrix", 
        icon: "images/matrix_dataspike.png",
        btn_desc: "<b>Data Spike</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Data Spike",
        book_src: "Core Rulebook, p.239",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "You send harmful instructions to a persona or device, causing Matrix damage to the target. Your attack has a Damage Value equal to your Attack rating, with one additional box of damage per net hit, and two additional boxes of damage for each mark you have on the target. This damage is Matrix damage (p. 228), resisted with the target's Device Rating + Firewall."
    },
    {
        action_id: "matrix_disarmdatabomb",
        action_class: "button button_matrix", 
        icon: "images/matrix_disarmdatabomb.png",
        btn_desc: "<b>Disarm Data Bomb</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Disarm Data Bomb",
        book_src: "Core Rulebook, p.239",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "",
        description: "You attempt to disarm a Data Bomb that you have detected (usually as the result of a Matrix Perception action). If you score any net hits, the Data Bomb is removed and deleted. If not, the Data Bomb activates, causing its damage and possibly destroying any file to which it was attached (assuming it was set to destroy the file)."
    },
    {
        action_id: "matrix_editfile",
        action_class: "button button_matrix", 
        icon: "images/matrix_editfile.png",
        btn_desc: "<b>Edit File</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Edit File",
        book_src: "Core Rulebook, p.239",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Edit File allows you to create, change, copy, delete, or protect any kind of file. The defender against this test is either the host holding the file or the owner of the file (if it's not on a host). Each action is enough to alter one detail of a file—a short paragraph of text, a single detail of an image, or two or three seconds of video or audio (you and your gamemaster can work out what exactly “one detail” means). Your gamemaster may impose penalties on the test if your edit is particularly intricate or tricky. If you want to perform a continuous edit, such as removing your teammates from a video feed, you need to perform this action once per Combat Turn for as long as you want to keep the edit going.<br><br>If you use this action to copy a file, you are the new file's owner. If the file you want to copy has protection on it, this action automatically fails. If the file has a Data Bomb, the Data Bomb goes off on you (so try to remember to scan files before you open them).<br><br>You can also use this action to set protection on a file if you're its owner. To protect a file, make a Simple Computer + Logic [Data Processing] test. The number of hits you get becomes the rating of the protected file. A protected file cannot be read, changed, deleted, or copied until its protection is broken."
    },
    {
        action_id: "matrix_enterexithost",
        action_class: "button button_matrix", 
        icon: "images/matrix_enterexithost.png",
        btn_desc: "<b>Enter/Exit Host</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Enter/Exit Host",
        book_src: "Core Rulebook, p.239",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 <br> <b>Test:</b> n/a</p>",
        description: "You enter a host that you have a mark on and your icon appears there, or you leave a host you're already in. There is no test for this action: a host allows anyone to enter if they've got a mark, and anyone inside can exit. The host might not be so welcoming once you're inside, of course, and some IC has the ability to keep you trapped in a host until you can break out.<br><br>When you leave a host, you return to the grid from which you entered."
    },
    {
        action_id: "matrix_erasemark",
        action_class: "button button_matrix", 
        icon: "images/matrix_erasemark.png",
        btn_desc: "<b>Erase Mark</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Erase Mark",
        book_src: "Core Rulebook, p.239",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> special <br> <b>Test:</b> Computer + Logic [Attack] v. Willpower + Firewall",
        description: "You eradicate a mark that has been placed on your persona or on another icon. To perform this action, you need three marks on the icon from which you are erasing a mark. You do not, however, need a mark on the icon that placed the mark in the first place. You can try to erase two marks in the same action at a –4 dice pool penalty, and three marks in one go at a –10 dice pool penalty; if you go for more than one mark, all of the marks must be on the same icon and from the same icon. You can't use this action to change the target's owner.<br><br>For example, an IC program has marked both you and your buddy. You roll your Computer + Logic (with your Attack program rating as the limit), opposed by the IC's rating (standing in for Willpower) + Firewall to erase its mark on your icon. You need three marks on your buddy's icon to erase the IC's marks on him, but he isn't the sharing type, so he's on his own for now."
    },
    {
        action_id: "matrix_erasesign",
        action_class: "button button_matrix", 
        icon: "images/matrix_erasesign.png",
        btn_desc: "<b>Erase Matrix Signature</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Erase Matrix Signature",
        book_src: "Core Rulebook, p.239",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> none <br> <b>Test:</b>  Computer + Resonance [Attack] v. (Signature Rating) x 2",
        description: "You eradicate a Matrix signature that has been left by a Resonance being, such as a technomancer or a sprite. If successful, the signature dissipates. You need to have a Resonance rating to attempt this action; unlike other actions that need Resonance, this one's a real Matrix Action, and an Attack one to boot, so you risk Matrix damage and Overwatch Score when you use it."
    },
    {
        action_id: "matrix_formatdevice",
        action_class: "button button_matrix", 
        icon: "images/matrix_formatdevice.png",
        btn_desc: "<b>Format Device</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Format Device",
        book_src: "Core Rulebook, p.239",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 3 <br> <b>Test:</b> Computer + Logic [Sleaze] v. Willpower + Firewall",
        description: "You rewrite the boot code for the device. The next time it would reboot, it instead shuts down for good, or until its software can be replaced (an Extended Software + Logic [Mental] (12, 1 hour) Test). A device that has been shut down in this fashion loses all of its wireless modifiers but can still be used as a normal mechanism (a door with a manual handle can be opened, a gun with a trigger can be fired, etc.) and cannot be accessed from the Matrix."
    },
    {
        action_id: "matrix_gridhop",
        action_class: "button button_matrix", 
        icon: "images/matrix_gridhop.png",
        btn_desc: "<b>Grid-Hop</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Grid-Hop",
        book_src: "Core Rulebook, p.240",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> none <br> <b>Test:</b> none (Data Processing action)",
        description: "You hop to another grid—for example, you might jump from the public grid to Seattle's Emerald City local grid. To do this, you must have access to your destination grid. If you do not have access, you can use Brute Force or Hack on the Fly to hop to another grid illegally. If you're inside a host, you need to leave the host before you can hop to another grid."
    },
    {
        action_id: "matrix_hackonthefly",
        action_class: "button button_matrix", 
        icon: "images/matrix_hackonthefly.png",
        btn_desc: "<b>Hack on the Fly</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Hack on the Fly",
        book_src: "Core Rulebook, p.240",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> none <br> <b>Test:</b> Hacking + Logic [Sleaze] v. Intuition + Firewall",
        description: "You can use this action to mark a target without getting the normal permissions. This is the action for hackers emphasizing their Sleaze over their Attack, making it an analog to Brute Force.<br><br>When targeting an icon, you put one mark on it, up to a maximum of three marks per icon. Additionally, every two full net hits counts as one hit on a Matrix Perception Test, so you can get some info along with your mark.<br><br>Before rolling, you can declare that you are trying for more than one mark. If you try for two marks in one shot, you take a –4 dice pool penalty on the attempt. If you try for three marks in one go, you take a –10 dice pool penalty.<br><br>You can also use this action to hop to a grid for which you don't have legitimate access. The defense dice pool in this case is 4 dice for a local grid or 6 dice for a global grid. If you succeed, instead of putting a mark on the grid, you hop to that grid immediately. Using Hack on the Fly to hop grids unsuccessfully doesn't alert the grid or its demiGOD the way most unsuccessful Sleaze actions do."
    },
    {
        action_id: "matrix_hide",
        action_class: "button button_matrix", 
        icon: "images/matrix_hide.png",
        btn_desc: "",
        title: "Hide",
        book_src: "Core Rulebook, p.240",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 0 <br> <b>Test:</b> Electronic Warfare + Intuition [Sleaze] v. Intuition + Data Processing",
        description: "You'll probably be spotted by another icon, even if you're running silent. You can use this action to make a target lose you. If you succeed, the target stops spotting you and needs to perform a new Matrix Perception action against you if it wants to find you again. You can't hide from an icon that has a mark on you, so you'll need to clear those before you can try this action."
    },
    {
        action_id: "matrix_jamsignals",
        action_class: "button button_matrix", 
        icon: "images/matrix_jamsignals.png",
        btn_desc: "<b>Jam Signals</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Jam Signals",
        book_src: "Core Rulebook, p.240",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> Owner <br> <b>Test:</b> Electronic Warfare + Logic [Attack]",
        description: "This action turns the wireless device you are using into a local jammer. As long as you do not use the device for any further Matrix actions, the device adds any hits you get on the test to the noise rating for all Matrix actions conducted by or targeting any devices within 100 meters. If you want selective jamming or directional jamming, buy a jammer—that's what they're for."
    },
    {
        action_id: "matrix_jird",
        action_class: "button button_matrix", 
        icon: "images/matrix_jird.png",
        btn_desc: "<b>Jump Into Rigged Device</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Jump Into Rigged Device",
        book_src: "Core Rulebook, p.241",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 3 <br> <b>Test:</b> Electronic Warfare + Logic [Data Processing] v. Willpower + Firewall",
        description: "You jump into a device that has a rigger adaptation, usually a vehicle or a drone. There's a list of things you need to have in order to jump into a device: you have to have three marks on the device you want to jump into, you have to be in VR, the device you want to jump into has to have a rigger adaptation, and you have to have a control rig. If you are the device's owner, or the device's owner has given you permission to jump into the device, you don't need to make a test. In the Matrix, the icon of the device you jumped into becomes part of your persona.<br><br>If someone else is already jumped into the device, you cannot attempt this action until he or she vacates."
    },
    {
        action_id: "matrix_perception",
        action_class: "button button_matrix", 
        icon: "images/matrix_perception.png",
        btn_desc: "<b>Matrix Perception</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Matrix Perception",
        book_src: "Core Rulebook, p.241",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> none <br> <b>Test:</b>  Computer + Intuition [Data Processing] (v. Logic + Sleaze)",
        description: ["This versatile and important action is used both for finding icons in the Matrix and for analyzing Matrix objects. When you use this action to analyze a Matrix object or scan the vicinity for silent-running icons, you make a Simple Test and your hits determine how much info you get. For each net hit scored, you can ask for one piece of information about the object - this could be type, a rating, how many marks it has on it,  any files it may be carrying, which grid it is using, whether any silent running icons are in the area, or any other pertinent Matrix information. You learn one fact per net hit. If you get a list of marks,  you can only recognize marks you have seen before or marks left by personas that you have marks on yourself. Otherwise you only get a count. <br><br>If you're trying to spot an icon that is father than 100 meters away, this is a Simple Test: the first hit lets you spot the target, and any additional hits can be used to get more information about it as mentioned above. If you're looking for an icon that is running silent (after you've determined that it's present), the test becomes an Opposed Test, with the target defending with Logic + Sleaze. Net hits are used just like you would for spotting distant targets, with the first one for spotting the target and the rest for analysis.",
                    "<h3>Matrix Spotting Table</h3><table><tr><th>Target is...</th><th>Not running silent</th><th>Running Silent</th></tr><tr><td>Within 100 meters</td><td>Automatic</td></tr><tr><td>Outside 100 meters</td><td>Simple Computer + Intuition [Data Processing]</td><td>Opposed Computer + Intuition [Data Processing] v. Logic + Sleaze Test</td></tr><tr><td>A host</td><td>Automatic</td></tr></table>"]

    },
    {
        action_id: "matrix_reboot",
        action_class: "button button_matrix", 
        icon: "images/matrix_reboot.png",
        btn_desc: "<b>Reboot Device</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Reboot Device",
        book_src: "Core Rulebook, p.242",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 3 <br> <b>Test:</b> Computer + Logic [Data Processing] v. Willpower + Firewall",
        description: "The device on which this action is performed shuts down and immediately reboots. The device comes back online at the end of the following Combat Turn. The device ceases electronic functions and disappears from the Matrix until its reboot time is over.<br><br>When you reboot the device your persona is on, your OS is reset to zero and all of your marks, as well as the ones others may have put on your icon, are erased. If you're in VR when you reboot, you suffer from dumpshock (see p. 229). When you come back online, your icon can be on any grid to which you have legitimate access, or the public grid if you have no other grid access. When you perform this action, you can choose a delay of any amount of time between the time the device shuts down and the time it comes back online. Anyone with physical access to the device can override this delay by hitting the power button, which starts the boot process and brings the device online at the end of the following Combat Turn.<br><br>This action only works on devices. It doesn't work on hosts, living beings (like technomancers, although they can “reboot” themselves, p. 251), or Resonance constructs (like sprites), and the only persona it works on is your own. If you're the owner of the device you're rebooting, you don't have to make a test. You can't use this action on a device that is link-locked (p. 229)."
    },
    {
        action_id: "matrix_sdb",
        action_class: "button button_matrix", 
        icon: "images/matrix_sdb.png",
        btn_desc: "<b>Set Data Bomb</b><br><br><i><i>Complex Action</i><br><u>Matrix Action</u></i>",
        title: "Set Data Bomb",
        book_src: "Core Rulebook, p.242",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 <br> <b>Test:</b> Software + Logic [Sleaze] v. (Device Rating x 2)",
        description: "You set a Data Bomb in a file. When you do, choose the rating of the Data Bomb, up to the net hits on your test. You also need to choose whether or not the Data Bomb will delete the file to which it is attached when activated, and you need to program the passcode required to deactivate it. A file can only have one Data Bomb on it at a time.<br><br>The Data Bomb is triggered when someone attempts to read, edit, copy, protect, delete, or put another Data Bomb on the file without using the already-in-place Data Bomb's passcode. When a Data Bomb goes off, it causes (Rating)D6 Matrix Damage (resisted normally) to the icon that tripped it, deletes the file (if it was set that way), and then is itself deleted. If the passcode is used, the Data Bomb doesn't activate. Instead, it remains attached to the file, waiting for the next guy.<br><br>A Data Bomb can be detected using Matrix Perception. If it's detected, it can be defused with the Disarm Data Bomb action; a disarmed Data Bomb is deleted. Damn."
    },
    {
        action_id: "matrix_snoop",
        action_class: "button button_matrix", 
        icon: "images/matrix_snoop.png",
        btn_desc: "<b>Snoop</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Snoop",
        book_src: "Core Rulebook, p.242",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 <br> <b>Test:</b> Electronic Warfare + Intuition [Sleaze] v. Logic + Firewall",
        description: ["This action lets you intercept Matrix traffic sent to and from your target for as long as you have the target marked. You can listen to, view, or read this data live, or you can save it for later playback/viewing if you have something to store it on (your deck will do).",
                    "<h3>Uses of Snoop</h3> Snooping is often used for more than just eavesdropping. If your target makes a commcall, you can note the person they called and try to find them online with a Matrix Perception action; if they're within 100 meters, you spot them right away (if they're not running silent; if they are, then it's back to the Matrix Perception Test)."]
    },
    {
        action_id: "matrix_spoofcom",
        action_class: "button button_matrix", 
        icon: "images/matrix_spoofcom.png",
        btn_desc: "<b>Spoof Command</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Spoof Command",
        book_src: "Core Rulebook, p.242",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 (see description) <br> <b>Test:</b> Hacking + Intuition [Sleaze] v. Logic + Firewall",
        description: "You spoof a device's owner's identity, making the device think that your command is a legitimate one from its owner. You need one mark on the icon you are imitating; you do not need a mark on the target. The opposing dice roll is still based on the target, though. This trick only works on devices and agents, not IC, sprites, hosts, personas, or any other icons."
    },
    {
        action_id: "matrix_traceicon",
        action_class: "button button_matrix", 
        icon: "images/matrix_traceicon.png",
        btn_desc: "<b>Trace Icon</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Trace Icon",
        book_src: "Core Rulebook, p.243",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 2 <br> <b>Test:</b>  Computer + Intuition [Data Processing] v. Willpower + Sleaze",
        description: "You find the physical location of a device or persona in the Matrix. After succeeding with this action, you know the target's location for as long as you have at least one mark on the target. This doesn't work on hosts because they generally have no physical location, or IC programs because they are confined to their hosts."
    },

    {
        action_id: "matrix_compilesprite",
        action_class: "button button_resonance", 
        icon: "images/matrix_compilesprite.png",
        btn_desc: "<b>Compile Sprite</b><br><br><i>Complex Action</i><br><i><u>Resonance Action</u></i>",
        title: "Compile Sprite",
        book_src: "Core Rulebook, p.250",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Resonance Action</i></u>",
        action_detail2: "<b>Test:</b> Compiling + Resonance [Level] v. Sprite Level",
        description: "You compile a sprite (p. 254)."
    },
    {
        action_id: "matrix_decompilesprite",
        action_class: "button button_resonance", 
        icon: "images/matrix_decompilesprite.png",
        btn_desc: "<b>Decompile Sprite</b><br><br><i>Complex Action</i><br><i><u>Resonance Action</u></i>",
        title: "Decompile Sprite",
        book_src: "Core Rulebook, p.250",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Resonance Action</i></u>",
        action_detail2: "<b>Test:</b> Decompiling + Resonance [Level] v. Sprite Rating (+ compiler's Resonance)",
        description: "You attempt to decompile a sprite (p. 254)."
    },
    {
        action_id: "matrix_killcf",
        action_class: "button button_resonance", 
        icon: "images/matrix_killcf.png",
        btn_desc: "<b>Kill Complex Form</b><br><br><i>Complex Action</i><br><i><u>Resonance Action</u></i>",
        title: "Kill Complex Form",
        book_src: "Core Rulebook, p.250",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Resonance Action</i></u>",
        action_detail2: "<b>Test:</b> Software + Resonance [Level] v. Complex Form Level + Resonance",
        description: "You attempt to kill a complex form (p. 251)."
    },
    {
        action_id: "matrix_registersprite",
        action_class: "button button_resonance", 
        icon: "images/matrix_registersprite.png",
        btn_desc: "<b>Register Sprite</b><br><br><i>Complex Action</i><br><i><u>Resonance Action</u></i>",
        title: "Register Sprite",
        book_src: "Core Rulebook, p.250",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Resonance Action</i></u>",
        action_detail2: "<b>Test:</b> Registering + Resonance [Level] v. Sprite Level x 2",
        description: "You register a sprite (p. 254)."
    },
    {
        action_id: "matrix_threadcf",
        action_class: "button button_resonance", 
        icon: "images/matrix_threadcf.png",
        btn_desc: "<b>Thread Complex Form</b><br><br><i>Complex Action</i><br><i><u>Resonance Action</u></i>",
        title: "Thread Complex Form",
        book_src: "Core Rulebook, p.250",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Resonance Action</i></u>",
        action_detail2: "<b>Test:</b> Software + Resonance [Level] v. special",
        description: "You thread a complex form (p. 251)."
    },
    {
        action_id: "action_aimburst",
        action_class: "button button_action", 
        icon: "images/action_aimburst.png",
        btn_desc: "<b>Aimed Burst</b><br><br><i>Complex Action</i>",
        title: "Aimed Burst",
        book_src: "Run & Gun, p.119",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "This is an attack from a Burst Fire-capable weapon (not Semi-Auto Burst) fired in such a way to increase damage instead of making it harder to avoid. Since it is a Complex Action tracking Progressive Recoil becomes very important. The attack loses the –2 penalty to the defender but gains +1 DV. It costs the firer three rounds of ammunition."
    },
    {
        action_id: "action_ballestra",
        action_class: "button button_martial", 
        icon: "images/action_ballestra.png",
        btn_desc: "<b>Ballestra</b><br><br><i>Complex Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Ballestra",
        book_src: "Run & Gun, p.119",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<i><u>Clubs/Blades Only</u></i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "The character lunges forward with a long step toward his opponent, effectively adding +1 to the Reach of the attack. The character over commits himself in the maneuver, leaving himself vulnerable. The character takes a –1 to any Defense Tests and cannot use any Active Defense techniques until after his next Action Phase"
    },
    {
        action_id: "action_brainblast",
        action_class: "button button_action", 
        icon: "images/action_brainblast.png",
        btn_desc: "<b>Brain Blaster</b><br><br><i>Complex Action</i>",
        title: "Brain Blaster",
        book_src: "Run & Gun, p.119",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Usually Full-Auto fire is designed to increase the chance to hit, not to put a lot of rounds in one place. This action focuses a Full-Auto Action into a tight little area and causes all sorts of pain and damage. Tracking Progressive Recoil becomes very important with this action. The attack gains +2 DV and costs the firer six rounds of ammunition."
    },
    {
        action_id: "action_doubletap",
        action_class: "button button_action", 
        icon: "images/action_doubletap.png",
        btn_desc: "<b>Double-Tap</b><br><br><i>Complex Action</i>",
        title: "Double-Tap",
        book_src: "Run & Gun, p.120",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A rapid pair of well-aimed shots from a Semi-Automatic-capable weapon fired in such a way to increase damage instead of making it harder to avoid. Tracking Progressive Recoil becomes very important with this Action. The attack gains +1DV and costs the firer two rounds of ammunition. There is no penalty to defensive rolls from this shot."
    },
    {
        action_id: "action_escape",
        action_class: "button button_action", 
        icon: "images/action_escape.png",
        btn_desc: "<b>Escape</b><br><br><i>Complex Action</i>",
        title: "Escape",
        book_src: "Run & Gun, p.120",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "To break out of a Subduing or Clinch, the character must succeed in an Unarmed Combat + Strength [Physical] Test with a threshold equal to the net hits scored on the opponent's original Subduing Test. Otherwise, the character remains locked in a grapple or clinch. Actions are limited by the opponent's previous action (Subduing or Clinch)."
    },
    {
        action_id: "action_enhsup",
        action_class: "button button_action", 
        icon: "images/action_enhsup.png",
        btn_desc: "<b>Enhanced Suppresion</b><br><br><i>Complex Action</i>",
        title: "Enhanced Suppresion",
        book_src: "Run & Gun, p.120",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "For use with suppressive fire (p. 179, SR5), this attack narrows the area of suppression horizontally but increases it vertically. The attack narrows the suppression zone to 5 meters at the end (instead of 10) but prevents targets within the affected area from being able to avoid the fire with the Drop Prone action. They can still use the Lucky Cover Edge Action to avoid the roll, but they continue to suffer all the normal penalties of being within a suppressed area."
    },
    {
        action_id: "action_evade",
        action_class: "button button_action", 
        icon: "images/action_evade.png",
        btn_desc: "<b>Evade</b><br><br><i>Complex Action</i>",
        title: "Evade",
        book_src: "Run & Gun, p.120",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "With a little room to move, agile characters can avoid the Interception attempts of their opponents without engaging in combat. Using a Complex Action in tandem with their movement for the Combat Turn, they can make an Agility + Gymnastics [Physical] (1) Test. Each hit above the threshold allows the character to move past one opponent who is within Interception range. Those opponents cannot use Interception against that character, unless they know the martial art maneuver Shadow Block (p. 125)."
    },
    {
        action_id: "action_flechette",
        action_class: "button button_action", 
        icon: "images/action_flechette.png",
        btn_desc: "<b>Flechette Supressive Fire</b><br><br><i>Complex Action</i>",
        title: "Flechette Supresive Fire",
        book_src: "Run & Gun, p.120",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: ["Avoiding flechette suppressive fire is like dodging a tsunami. Suppressive Fire with flechette (f) ammo can make an attack over a wide area virtually unavoidable. These attacks function similar to Enhanced Suppression (see above) and prevents targets from using the Drop Prone action to avoid the attack and suffers no loss of width, quite the opposite. Suppressive Fire with flechette ammunition has a wide range of effects, covered by the Flechette Suppressive Fire Tables. Effects are arranged by Choke Setting. Narrow Spread Choke settings only confer the Enhanced Suppression and their normal effects.",
            "<h3>Flechette Suppressive Fire Tables</h3>",
            "<h4>Narrow Spread</h4><table><tr><th>Range</th><th>DV Adjustment</th><th>Accuracy Adjustment</th><th>Defense Adjustment</th><th>Extra Width</th></tr><tr><td>Short</td><td>-1</td><td>-</td><td>-3</td><td>4 meters</td></tr><tr><td>Medium</td><td>-3</td><td>-</td><td>-3</td><td>8 meters</td></tr><tr><td>Long</td><td>-5</td><td>-1</td><td>-3</td><td>12 meters</td></tr><tr><td>Extreme</td><td>-7</td><td>-1</td><td>-3</td><td>16 meters</td></tr></table>",
            "<h4>Medium Spread</h4><table><tr><th>Range</th><th>DV Adjustment</th><th>Accuracy Adjustment</th><th>Defense Adjustment</th><th>Extra Width</th></tr><tr><td>Short</td><td>-3</td><td>-</td><td>-5</td><td>6 meters</td></tr><tr><td>Medium</td><td>-5</td><td>-</td><td>-5</td><td>12 meters</td></tr><tr><td>Long</td><td>-7</td><td>-1</td><td>-3</td><td>18 meters</td></tr><tr><td>Extreme</td><td>-9</td><td>-1</td><td>-3</td><td>24 meters</td></tr></table>"
        ]
    },
    {
        action_id: "action_flyingkick",
        action_class: "button button_martial", 
        icon: "images/action_flyingkick.png",
        btn_desc: "<b>Flying Kick</b><br><br><i>Complex Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Flying Kick",
        book_src: "Run & Gun, p.121",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Use of this action requires Martial Art training.</i></u>",
        action_detail2: "",
        description: "Covering scissor, butterfly, crescent, hook, and reverse roundhouse kicks, this Action offers both range and power to the unarmed attack. The character must be at least a meter away from the opponent and be able to move toward the opponent to perform this action. A Flying Kick Action gives both +1 Reach and +1 dice pool bonus to the unarmed attack. If the Flying Kick Action is unsuccessful, the character becomes off balance, suffering a –1 dice pool penalty to Defense Tests until the character's next Action Phase."
    },
    {
        action_id: "action_fulloffense",
        action_class: "button button_martial", 
        icon: "images/action_fulloffense.png",
        btn_desc: "<b>Full Offense</b><br><br><i>Complex Action</i><br><i><u>Martial Art Required</u></i><br><i><b>-5 Initiative Score</b></i>",
        title: "Full Offense",
        book_src: "Run & Gun, p.121",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "A Full Offense attack occurs when a character accepts that he's going to get hurt and doesn't care so long as he hurts his opponent more. This is also the usu- al state of drunken brawlers, though their accuracy tends to be diminished. The attacking character receives a +2 dice pool modifier to their Close Combat skill test, but may not use any Defensive Interrupt Actions for that Action Phase (Block, Dodge, Full Defense, Parry, etc.). They also adjust their Initiative Score by –5. "
    },
    {
        action_id: "action_halfsword",
        action_class: "button button_martial", 
        icon: "images/action_halfsword.png",
        btn_desc: "<b>Half Sword</b><br><br><i>Complex Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Half Sword",
        book_src: "Run & Gun, p.121",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<i><u>Blade Only</u></i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "This odd technique involves grabbing the center part of the blade for a more forceful thrust against an armored target with the intent of piercing the target's armor. Back in the days of plate armor, the Half Sword action was like using the sword as a crowbar and peeling back the armor. Today's armor is more flexible, but the intent is the same. With a successful attack, the character improves their AP by 2 for the weapon. If the character fails, he takes a –2 penalty to his next action (not counting Defense Tests) and cannot use the Parry or Block Defensive Actions until his next Action Phase. Regardless of success or failure, the character has to Ready the Weapon (as he's holding it in an unusual manner) in order to attack again. This move cannot be combined with Two Weapon fighting as it requires both hands. The weapon must be a blade with at least a Reach of 1."
    },
    {
        action_id: "action_haymaker",
        action_class: "button button_martial", 
        icon: "images/action_haymaker.png",
        btn_desc: "<b>Haymaker</b><br><br><i>Complex Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Haymaker",
        book_src: "Run & Gun, p.121",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<i><u>Close Combat Only</u></i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "While the Pouncing Dragon technique has the character using gravity to his advantage, not every combat allows the character to have superior position. With the Haymaker, the character uses centrifugal force in order gain power in the attack. This action is wild and obvious to an opponent. With this attack, the character gives the opponent +2 to their Defense Test. If successful the character gets +1 DV. "
    },
    {
        action_id: "action_herding",
        action_class: "button button_martial", 
        icon: "images/action_herding.png",
        btn_desc: "<b>Herding</b><br><br><i>Complex Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Herding",
        book_src: "Run & Gun, p.121",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Use of this action requires Martial Art training.</i></u>",
        action_detail2: "",
        description: "As if engaging in some sort of masochistic dance, the character can use attacks and feints to maneuver an opponent into a bad position, such as on top of a land mine or against an open elevator shaft. On a successful Close Combat Attack, the character deals no damage to his opponent. Instead, the character can move the opponent 1 meter per net hit in the direction of the character's choosing, up to the Walking rate of the character or opponent, whichever is less. A character may attempt herding multiple opponents by splitting his dice pool as normal (Multiple Attacks, p. 196, SR5). The distance that the character can herd multiple opponents is determined on an individual opponent basis."
    },
    {
        action_id: "action_playingpossum",
        action_class: "button button_action", 
        icon: "images/action_playingpossum.png",
        btn_desc: "<b>Playing Possum</b><br><br><i>Complex Action</i>",
        title: "Playing Possum",
        book_src: "Run & Gun, p.122",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "With a little acting skill, a character can gain themselves a nice advantage by playing up their injuries or pretending they are injured. The character needs to take a Complex Action and perform a Con + Charisma [Social] vs. Con + Charisma [Social] Opposed Test or Performance + Charisma [Social] vs. Charisma + Willpower Test in order to make themselves look seriously injured and out of the fight. This is one of the few places where being injured works in a character's favor. For every three boxes of damage the character has, he gains a +1 dice pool bonus to his roll (and ignores the injury modifier). The character's net hits become the threshold for a Perception Test for anyone the character attacks to avoid being caught unaware by the character. Unaware characters do not get a Defense Test when they are attacked."
    },
    {
        action_id: "action_pouncedragon",
        action_class: "button button_martial", 
        icon: "images/action_pouncedragon.png",
        btn_desc: "<b>Pouncing Dragon</b><br><br><i>Complex Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Pouncing Dragon",
        book_src: "Run & Gun, p.122",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<i><u>Close Combat Only</u></i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "Pouncing Dragon is a close-combat attack where the character has superior position to the opponent and uses gravity to their advantage. This move can be made from a position standing above the opponent, the opponent being prone or standing below the character, or it can be executed when the character is in a Clinch with the opponent, both of them are on the ground, and the character's Superior Position advantage is that they are on top of the opponent. Typically learned through mixed martial arts, various wrestling arts, or weapon martial arts as a way to dispatch fallen opponents, Pouncing Dragon requires characters to take advantage of gravity and put their weight behind the attack. Besides the Superior Position modifier, the character gets +2 DV on a successful attack. After the attack, the character is at the same level as the opponent and loses the Superior Position advantage."
    },
    {
        action_id: "action_sacrificemove",
        action_class: "button button_action", 
        icon: "images/action_sacrificemove.png",
        btn_desc: "<b>Sacrifice Move</b><br><br><i>Complex Action</i>",
        title: "Sacrifice Move",
        book_src: "Run & Gun, p.123",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<i><u>Close Combat Only</u></i>",
        action_detail2: "",
        description: "Sacrifice Move is like a Shove, but it is a Complex Action. The character is attempting to move an opponent and throws his whole body into the attempt. The test and results are similar to Shove, but the attacking character uses Strength + Body plus net hits instead of just Strength + net hits. On a successful attempt, both the character and opponent are Prone."
    },
    {
        action_id: "action_readthedef",
        action_class: "button button_action", 
        icon: "images/action_readthedef.png",
        btn_desc: "<b>Reading The Defense</b><br><br><i>Complex Action</i>",
        title: "Reading The Defense",
        book_src: "Run & Gun, p.123",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<i><u>Melee Only</u></i>",
        action_detail2: "",
        description: "Sometimes the best defense is a good offense. Characters spend a Complex Action and make a (Melee Skill) + Intuition [Mental] (3) Test studying their opponent's style while engaged in combat, taking the time to read an opponent's defense. This action can only be performed while a character is engaged in combat with an opponent. After the character has spent their Complex Action they gain a +3 dice pool bonus on their next melee attack against that opponent. If they fail on the test, though, they misread the attacker's intentions and instead take a –1 penalty on their next melee attack against the opponent. A glitch makes that penalty even worse, while a critical glitch means the character focused so intently on the attack that they dropped their own defense, and must take a –3 dice pool penalty (or greater at the gamemaster's discretion) on their Defense Test against the next attack from any source."
    },
    {
        action_id: "action_subduing",
        action_class: "button button_action", 
        icon: "images/action_subduing.png",
        btn_desc: "<b>Subduing</b><br><br><i>Complex Action</i>",
        title: "Subduing",
        book_src: "Run & Gun, p.123",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A Subduing Action is grappling the opponent in either a choke hold or a joint lock that brings asphyxiation to the brain or pain to a joint or body part. The character follows the standard rules for Subduing (p. 195, SR5) and must spend a Complex Action per Action Phase to maintain the Subduing. As part of that action, they can perform any of the allowed options, and the opponent cannot take an action that requires Movement. A character can end the Subduing as a Free Action, but still be in contact with the opponent for that Action Phase. Subduing Actions can be done as an Interrupt Action (–5 Initiative Score) by a character on an opponent who has successfully completed a touch-only attack against him."
    },
    {
        action_id: "action_touchonlyattack",
        action_class: "button button_action", 
        icon: "images/action_touchonlyattack.png",
        btn_desc: "<b>Touch-Only Attack</b><br><br><i>Complex Action</i>",
        title: "Touch-Only Attack",
        book_src: "Run & Gun, p.124",
        action_type: "<i>Complex Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "The character makes a Close Combat Skill Attack Test (with the +2, touch-only advantage) to make contact with the opponent. If successful, the character does no damage, but is in contact with the opponent for that Action Phase or until the opponent moves, risking an Intercept Action (see Interception, p. 194, SR5). Touch attacks have the disadvantage of being more easily grappled in a Subduing or Clinch Action by an opponent. Characters defending against a Grapple or Clinch after making a touch-only attack against an opponent receive a –2 dice pool penalty against that opponent.<br><br>Weapons such as the shock glove or baton can inflict damage during a touch-only attack. These attacks don't benefit from net hits from the attack to increase Damage Value. Using the weapon to cause damage with a touch-only attack makes it the only attack action the character can make during that Action Phase."
    },
    {
        action_id: "matrix_confusepilot",
        action_class: "button button_matrix", 
        icon: "images/matrix_confusepilot.png",
        btn_desc: "<b>Confuse Pilot</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Confuse Pilot",
        book_src: "Rigger 5.0 p.30",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Electronic Warfare + Logic [Attack] v. Pilot + Firewall</p>",
        description: "You send a stream of code to a device with a pilot (usually a drone, but sometimes an autonomous vehicle or gun emplacement) that resembles valid instructions but is in fact gobbledygook. If you succeed, the pilot becomes confused, and makes an immediate Simple Pilot x 2 Test to figure out what it's going to do next (p. 269, SR5)—the threshold for this test is equal to half of your net hits. Your RCC's Noise Reduction Rating is added as a dice pool bonus for this action."
    },
    {
        action_id: "matrix_suppressnoise",
        action_class: "button button_matrix", 
        icon: "images/matrix_suppressnoise.png",
        btn_desc: "<b>Suppress Noise</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Suppress Noise",
        book_src: "Rigger 5.0 p.30",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> Owner <br> <b>Test:</b> Electronic Warfare + Logic [Data Processing]</p>",
        description: "As described on p. 268, SR5, this action allows riggers to use their RCC to reduce noise between themselves and their vehicles or drones. Reduce noise by the hits on this test, cumulative with any other forms of noise reduction. This effect lasts for the remainder of the current Combat Turn. Your RCC's Noise Reduction rating is added as a dice pool bonus for this action."
    },
    {
        action_id: "matrix_targetdevice",
        action_class: "button button_matrix", 
        icon: "images/matrix_targetdevice.png",
        btn_desc: "<b>Target Device</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Target Device",
        book_src: "Rigger 5.0 p.30",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Electronic Warfare + Logic [Data Processing] v. Willpower + Firewall</p>",
        description: "Pick a wireless-enabled device you've spotted on the Matrix. You can target that device and feed targeting data to any pilot program or person with a Sensor rating or smartlink that is slaved to your RCC. For the rest of the Combat Turn, the slaved attackers receive a dice pool bonus equal to your net hits when targeting the device you're tracking for them. Your RCC's Noise Reduction rating is added as a dice pool bonus for this action."
    },
    {
        action_id: "matrix_iamthefirewall",
        action_class: "button button_matrix", 
        icon: "images/matrix_iamthefirewall.png",
        btn_desc: "<b>I Am The Firewall</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "I Am The Firewall",
        book_src: "Kill Code p.38",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Computer + Intuition [Data Processing]</p>",
        description: "<i>Instead of attacking, the hacker engages threat-highlighting software, giving allies an edge to their defenses.</i><br><br> I Am the Firewall allows the hacker to give a Defense test bonus to all allies with access to an AR feed from the user. The number of bonus dice is equal to the number of hits on a Computer + Intuition [Data Processing] Test. This bonus lasts until the beginning of the hacker's next Initiative Pass. The hacker can only share their feed with a number of users equal to or less than their Data Processing attribute.<br><br>When you take this action as an Interrupt Action, your Initiative Score is reduced by 5."
    },
    {
        action_id: "matrix_haywire",
        action_class: "button button_matrix", 
        icon: "images/matrix_haywire.png",
        btn_desc: "<b>Haywire</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Haywire",
        book_src: "Kill Code p.38",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Cybercombat + Logic [Attack] v. Willpower + Firewall</p>",
        description: "<i>Smartguns cease to offer any benefits, commcalls can't be made, and sensor readings go dark. Unwitting users may assume their device is glitching and attempt to click past the error messages once or twice, before realizing the futility.</i><br><br>Target must be a persona not running in VR. Haywire disables all of the target's PAN-related functions. Physical devices still function, so smartguns can still fire and chemsuits still offer protection, but without wireless or PAN functions. This effect lasts until the target succeeds an extended Computer + Logic [Data Processing] (Hacker's Net Hits, Simple Action) test with a threshold equal to the net hits from the attacker's roll; each attempt takes a simple action. The target may simply reset their device and reboot it with a Complex Action; the device will be back online at the end of the following Combat Turn, which takes one minute. Glitching the test to fix the device adds an additional net hit to the attacker's roll. A critical glitch causes all the devices on the PAN to require an OS reinstall. This takes multiple hours and a connection to a persona-enabled device."
    },
    {
        action_id: "matrix_masquerade",
        action_class: "button button_matrix", 
        icon: "images/matrix_masquerade.png",
        btn_desc: "<b>Masquerade</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Masquerade",
        book_src: "Kill Code p.39",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 2 on impersonated persona, 2 on the icon you're trying to fool <br> <b>Test:</b> Hacking + Intuition [Sleaze] v. Logic + Firewall</p>",
        description: "<i>You may not be able to actually use someone else's persona, but you can fake it well enough so that your enemies can't tell. As far as they know, you truly are one of the Wuxing Quints.</i><br><br>This action allows a hacker to impersonate a persona on the Matrix. Since persona data is updated in real time, this action requires 2 marks on one target (the persona being impersonated) and 2 marks on a second target (the icon you are trying to fool). For every net hit scored on a Hacking + Intuition [Sleaze] v. Logic + Firewall against the second target, you have convinced them you are target one for one minute. This can be used to impersonate someone online, intercept their calls, use their social media, rummage through their email history, or other creative mischief, but processes like changing device owners or performing major financial actions (like bank transfers) have too many double-checks for Masquerade to work. If the persona you're impersonating logs off, those marks are immediately lost, and the disguise drops. While masquerading, you are never considered the owner with regard to any of the impersonated persona's devices."
    },
    {
        action_id: "matrix_subvertinfr",
        action_class: "button button_matrix", 
        icon: "images/matrix_subvertinfr.png",
        btn_desc: "<b>Subvert Infrastruction</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Subvert Infrastruction",
        book_src: "Kill Code p.39",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 <br> <b>Test:</b> Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall</p>",
        description: "<i>Sometimes, you need all the traffic lights to turn green for you and red for your enemies. And you want a free soyda along the way.</i><br><br>This action allows a decker or technomancer to slightly alter the operation of multiple physical devices so they respond to the hacker's commands. If the hacker has at least 1 mark on the host, a successful Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall Test allows them to control one similar simple device (traffic lights, vending machines, home appliances, desk lamps, etc., at gamemaster discretion) slaved to that host for every net hit. This action cannot be used to make an attack. The hacker can sustain controlling these devices as a Complex Action each Combat Turn."
    },
    {
        action_id: "matrix_watchdog",
        action_class: "button button_matrix", 
        icon: "images/matrix_watchdog.png",
        btn_desc: "<b>Watchdog</b><br><br><i>Complex Action</i><br><i><u>Matrix Action</u></i>",
        title: "Watchdog",
        book_src: "Kill Code p.40",
        action_type: "<i>Complex Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Electronic Warfare + Logic [Sleaze] v. Logic + Firewall</p>",
        description: "<i>Every breath you take, every move you make, every bond you break, every step you take …</i><br><br>Target must be a persona or device. If successful, place one mark on the target. The user is now aware of the Matrix actions the target is going to use before they use them, and they may attempt to stop them. A Watchdog mark allows the hacker to use Haywire or Popup as Interrupt Actions (for -10 initiative) or Squelch as an Interrupt Action (for -5 initiative) against the target with the Watchdog mark. This ability lasts as long as the target is marked by the user."
    }
]