const sr_action_free= [
    {
        action_id: "action_callashot",
        action_class: "button button_action",
        icon: "images/action_callashot.png",
        btn_desc: "<b>Call A Shot</b><br><br><i>Free Action</i>",
        title:"Call A Shot",
        book_src: "Core Rulebook, p.163",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may call a shot (aim for a vulnerable portion of a target) with this Free Action; see Called Shots, p. 178. This action must be combined with a Fire Weapon, Throw Weapon, or Melee Attack Action."
    },
    {
        action_id: "action_cldm",
        action_class: "button button_action", 
        icon: "images/action_cldm.png",
        btn_desc: "<b>Change Linked Device Mode</b><br><br><i>Free Action</i>",
        title: "Change Linked Device Mode",
        book_src: "Core Rulebook, p.163",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may use a Free Action to activate, deactivate, or switch the mode on any device that he is linked to by a direct neural interface through either a wired or wireless link. This includes activating cyberware, changing a smartgun's firing mode, changing a smartlinked shotgun's choke, deactivating thermographic vision, switching a commlink to hidden mode, turning a device's wireless functionality off, and so on. Note that it takes longer to interact with some devices, as noted in individual gear descriptions."
    },
    {
        action_id: "matrix_controldevice",
        action_class: "button button_matrix", 
        icon: "images/matrix_controldevice1.png",
        btn_desc: "<b>Control Device (1 mark)</b><br><br><i>Free Action</i><br><i><u>Matrix Action</u></i>",
        title: "Control Device",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Variable Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> varies <br> <b>Test:</b>  (as action) [Data Processing (or special)] v. (as action) or Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall",
        description: "You perform an action through a device you control(or at least control sufficiently), using your commlink or deck like a remote control or video-game controller. The dice pool of any test you make using this action uses the rating of the appropriate skill and attribute you would use if you were performing the action normally. For example, firing a drone-mounted weapon at a target requires a Gunnery + Agility test, and using a remote underwater welder calls for a Nautical Mechanic + Logic test. All actions you take while controlling a device use either the normal limit for that action or your Data Processing rating, whichever is lower. If there is no test associated with the action you want the device to perform (such as unlocking a maglock or ejecting a clip from a pistol), you must succeed in an Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall test to perform the action. <br><br> You can use this action to control multiple devices at once. If you are the owner of all devices being commanded and they are all being commanded to do exactly the same thing, taking this action costs nothing extra. Otherwise, you must split your dice pool into a number of groups equal to the number of devices you want to control with a single action. <br><br> The type of action this is (i.e., Free, Simple, Standard, and Complex) is the same as the type of action attempted with the device, and it requires 1 mark for Free Actions, 2 marks for Simple Actions, and 3 marks for Standard or Complex Actions. <br><br> This action is a Sleaze action whenever you use your Sleaze as a limit in the test, which incurs the same risk of Overwatch Score and consequences of failure as all Sleaze actions."
    },
    {
        action_id: "action_dropobj",
        action_class: "button button_action",
        icon: "images/action_dropobj.png",
        btn_desc: "<b>Drop Object</b><br><br><i>Free Action</i>",
        title: "Drop Object",
        book_src: "Core Rulebook, p.163",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may drop a held object as a Free Action. If he is holding an object in each hand, he may drop both objects as a single Free Action. At the gamemaster's discretion, dropped items may suffer damage from being dropped if they are fragile or dropped in a hostile environment."
    },
    {
        action_id: "action_dropprone",
        action_class: "button button_action",
        icon: "images/action_dropprone.png",
        btn_desc: "<b>Drop Prone</b><br><br><i>Free Action</i>",
        title: "Drop Prone",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may kneel or drop prone as a Free Action, as long as he is not surprised (see Surprise, p. 192). A character who is surprised may not drop prone."
    },
    {
        action_id: "action_ejectsmc",
        action_class: "button button_action",
        icon: "images/action_ejectsmc.png",
        btn_desc: "<b>Eject Smartgun Clip</b><br><br><i>Free Action</i>",
        title: "Eject Smartgun Clip",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character linked to a ready smartgun may use a mental command to eject the weapon's clip. It still takes a separate Simple Action to insert a new, fresh clip (see Smartgun System, p. 433)."
    },
    {
        action_id: "action_gesture",
        action_class: "button button_action",
        icon: "images/action_gesture.png",
        btn_desc: "<b>Gesture</b><br><br><i>Free Action</i>",
        title: "Gesture",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may communicate with a few quick gestures as a Free Action. Characters unfamiliar with the  gestures may make an Intuition (2) Test to determine what the gesture means."
    },
    {
        action_id: "action_multiattack",
        action_class: "button button_action",
        icon: "images/action_multiattack.png",
        btn_desc: "<b>Multiple Attacks</b><br><br><i>Free Action</i>",
        title: "Multiple Attacks",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may use a Free Action to attack multiple targets in a single action (see Multiple Attacks, p. 196) by splitting their dice pool. This action must be combined with a Fire Weapon Action, Throw Weapon Action, Melee Attack Action, Reckless Spellcasting, or Cast Spell Action."
    },
    {
        action_id: "action_run",
        action_class: "button button_action",
        icon: "images/action_run.png",
        btn_desc: "<b>Run</b><br><br><i>Free Action</i>",
        title: "Run",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Running uses a Free Action and inflicts Running movement modifiers. Running is any movement that exceeds the character's Walking Movement Rate in a single Combat Turn (see Movement, p. 161)."
    },
    {
        action_id: "action_talk",
        action_class: "button button_action",
        icon: "images/action_talk.png",
        btn_desc: "<b>Speak/Text/Transmit Phrase</b><br><br><i>Free Action</i>",
        title: "Speak/Text/Transmit Phrase",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Free Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "One short phrase of verbal communication is a Free Action. If the character wants to speak more, each additional phrase or sentence requires a Free Action. The gamemaster should be careful to control excessive, unrealistic conversations within the span of a single action during a 3-second Combat Turn. If the gamemaster and players prefer more elaborate communications, parameters should be laid out before the mission begins. Characters who are equipped to send text messages through a direct neural interface connection with their commlink may also send short messages as a Free Action."
    },
    {
        action_id: "special_cyberdeck1",
        action_class: "button button_action", 
        icon: "images/special_cyberdeck1.png",
        btn_desc: "<b>Load Program</b><br><br><i>Free Action</i>",
        title: "Reconfiguring Your Deck",
        book_src: "Core Rulebook, p.227",
        action_type: "",
        action_detail1: "",
        action_detail2: "",
        description: "You can reconfigure your deck whenever you like, rebalancing your software loadout, changing the allocation of Matrix attributes  or re-arranging the programs currently available to you. Doing this is a Free Action that you may only perform on your own Action  Phase. This is not a Matrix action. When you reconfigure your deck, you can either switch two of your deck's Matrix attributes, or swap a running program with a program you have stored on your deck that is not running. Additionally, you can load a program you own into a currently unused slot, or unload a program and leave an open slot.<br> For example, let's say you're hanging out in JackPoint and some asshat insults your avatar. You're feeling surly, so you take a swing at him. You weren't planning on mixing things up tonight, so at the moment your Attack is 2 and your Data Processing is 5. You'd prefer them to be the other way around, so you take a Free Action to swap the two attributes before you make your attack. With your Attack rating at 5, you'll be able to land the full force of whatever blow you've aimed at the mouthy jerk."
    },
    {
        action_id: "special_cyberdeck2",
        action_class: "button button_action", 
        icon: "images/special_cyberdeck2.png",
        btn_desc: "<b>Switch Two Matrix Attributes</b><br><br><i>Free Action</i>",
        title: "Reconfiguring Your Deck",
        book_src: "Core Rulebook, p.227",
        action_type: "",
        action_detail1: "",
        action_detail2: "",
        description: "You can reconfigure your deck whenever you like, rebalancing your software loadout, changing the allocation of Matrix attributes  or re-arranging the programs currently available to you. Doing this is a Free Action that you may only perform on your own Action  Phase. This is not a Matrix action. When you reconfigure your deck, you can either switch two of your deck's Matrix attributes, or swap a running program with a program you have stored on your deck that is not running. Additionally, you can load a program you own into a currently unused slot, or unload a program and leave an open slot.<br> For example, let's say you're hanging out in JackPoint and some asshat insults your avatar. You're feeling surly, so you take a swing at him. You weren't planning on mixing things up tonight, so at the moment your Attack is 2 and your Data Processing is 5. You'd prefer them to be the other way around, so you take a Free Action to swap the two attributes before you make your attack. With your Attack rating at 5, you'll be able to land the full force of whatever blow you've aimed at the mouthy jerk."
    },
    {
        action_id: "special_cyberdeck3",
        action_class: "button button_action", 
        icon: "images/special_cyberdeck3.png",
        btn_desc: "<b>Swap Two Programs</b><br><br><i>Free Action</i>",
        title: "Reconfiguring Your Deck",
        book_src: "Core Rulebook, p.227",
        action_type: "",
        action_detail1: "",
        action_detail2: "",
        description: "You can reconfigure your deck whenever you like, rebalancing your software loadout, changing the allocation of Matrix attributes  or re-arranging the programs currently available to you. Doing this is a Free Action that you may only perform on your own Action  Phase. This is not a Matrix action. When you reconfigure your deck, you can either switch two of your deck's Matrix attributes, or swap a running program with a program you have stored on your deck that is not running. Additionally, you can load a program you own into a currently unused slot, or unload a program and leave an open slot.<br> For example, let's say you're hanging out in JackPoint and some asshat insults your avatar. You're feeling surly, so you take a swing at him. You weren't planning on mixing things up tonight, so at the moment your Attack is 2 and your Data Processing is 5. You'd prefer them to be the other way around, so you take a Free Action to swap the two attributes before you make your attack. With your Attack rating at 5, you'll be able to land the full force of whatever blow you've aimed at the mouthy jerk."
    },
    {
        action_id: "special_cyberdeck4",
        action_class: "button button_action", 
        icon: "images/special_cyberdeck4.png",
        btn_desc: "<b>Unload Program</b><br><br><i>Free Action</i>",
        title: "Reconfiguring Your Deck",
        book_src: "Core Rulebook, p.227",
        action_type: "",
        action_detail1: "",
        action_detail2: "",
        description: "You can reconfigure your deck whenever you like, rebalancing your software loadout, changing the allocation of Matrix attributes  or re-arranging the programs currently available to you. Doing this is a Free Action that you may only perform on your own Action  Phase. This is not a Matrix action. When you reconfigure your deck, you can either switch two of your deck's Matrix attributes, or swap a running program with a program you have stored on your deck that is not running. Additionally, you can load a program you own into a currently unused slot, or unload a program and leave an open slot.<br> For example, let's say you're hanging out in JackPoint and some asshat insults your avatar. You're feeling surly, so you take a swing at him. You weren't planning on mixing things up tonight, so at the moment your Attack is 2 and your Data Processing is 5. You'd prefer them to be the other way around, so you take a Free Action to swap the two attributes before you make your attack. With your Attack rating at 5, you'll be able to land the full force of whatever blow you've aimed at the mouthy jerk."
    },
    {
        action_id: "action_preblock",
        action_class: "button button_action",
        icon: "images/action_block.png",
        btn_desc: "<b>Pre-Emptive Block</b><br><br><i>Free Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Pre-Emptive Block",
        book_src: "Run & Gun, p.122",
        action_type: "<i>Free Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "The character chooses to reduce their Initiative Score by 5 in order to be on the lookout for any incoming attacks to Block. This action allows the character to use the Block Defense option (p. 170, SR5) for an entire Combat Turn for the price of the normal Interrupt Action by making their defense active instead of reactive. This action can only be used during a character's Action Phase."
    },
    {
        action_id: "action_predodge",
        action_class: "button button_action",
        icon: "images/action_dodge.png",
        btn_desc: "<b>Pre-Emptive Dodge</b><br><br><i>Free Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Pre-Emptive Dodge",
        book_src: "Run & Gun, p.122",
        action_type: "<i>Free Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "The character chooses to reduce their Initiative Score by 5 in order to be on the lookout for any incoming attacks to Dodge. This action allows the character to use the Dodge Defense option (p. 170, SR5) for an entire Combat Turn for the price of the normal Interrupt Action by making their defense active instead of reactive. This Free Action can only be used during a character's Action Phase."
    },
    {
        action_id: "action_preparry",
        action_class: "button button_action",
        icon: "images/action_parry.png",
        btn_desc: "<b>Pre-Emptive Parry</b><br><br><i>Free Action</i><br><i><b>-5 Initiative Score</b></i>",
        title: "Pre-Emptive Parry",
        book_src: "Run & Gun, p.122",
        action_type: "<i>Free Action</i>",
        action_detail1: "<i>-5 Initiative Score</i>",
        action_detail2: "",
        description: "The character chooses to reduce their Initiative Score by 5 in order to be on the lookout for any incoming attacks to Parry. This action allows the character to use the Parry Defense option (p. 170, SR5) for an entire Combat Turn for the price of the normal Interrupt Action by making their defense active instead of reactive. This Free Action can only be used during a character's Action Phase."
    },
    {
        action_id: "matrix_dtl", 
        action_class: "button button_matrix", 
        icon: "images/matrix_dtl.png", 
        btn_desc: "<b>Detect Target Lock</b><br><br><i>Free Action</i>", 
        title: "Detect Target Lock", 
        book_src: "Rigger 5.0 p.30",
        action_type: "<i>Free Action</i>", 
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> Owner <br> <b>Test:</b> Computer + Logic [Data Processing] (2) ",
        description: "Passive targeting and active targeting with sensors are described on p. 184 of SR5. An active target lock sends wireless and other signals that hackers and riggers have learned to detect. The RCC, commlink, or deck that you're using must be wireless-enabled to perform this action. Your RCC's Noise Reduction rating is added as a dice pool bonus for this action."
    }

];