sr_action_simple = [
    {
        action_id: "action_actfocus",
        action_class: "button button_action",
        icon: "images/action_actfocus.png",
        btn_desc: "<b>Activate Focus</b><br><br><i>Simple Action</i>",
        title: "Activate Focus",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may activate a focus they are carrying with a Simple Action.",

    },
    {
        action_id: "action_callspirit",
        action_class: "button button_action",
        icon: "images/action_callspirit.png",
        btn_desc: "<b>Call Spirit</b><br><br><i>Simple Action</i>",
        title: "Call Spirit",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "This action is used to call a spirit that has already been summoned and placed on standby.",

    },
    {
        action_id: "action_cdm",
        action_class: "button button_action",
        icon: "images/action_cdm.png",
        btn_desc: "<b>Change Device Mode</b><br><br><i>Simple Action</i>",
        title: "Change Device Mode",
        book_src: "Core Rulebook, p.164",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may use a Simple Action to activate, deactivate, or change the mode on any device with a simple switch, a virtual button, or a command from a commlink or other control device through either a wired or wireless link. This includes changing a gun's firing mode, changing a shotgun's choke, changing vision systems, switching a commlink to hidden mode, turning a device's wireless functionality off, and so on. It takes longer to interact with some devices; check individual gear descriptions.",

    },
    {
        action_id: "action_cgm",
        action_class: "button button_action",
        icon: "images/action_cgm.png",
        btn_desc: "<b>Change Gun Mode</b><br><br><i>Simple Action</i>",
        title: "Change Gun Mode",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character holding a ready firearm can change its firing mode via a Simple Action. If the weapon is a properly linked smartgun, it costs only a Free Action to change the mode (see Firearms, p. 424, and Smartgun Systems, p. 433). This includes changing a shotgun's choke if the gun does not have a smartgun link (see Shotguns, p. 429).",

    },
    {
        action_id: "action_commandspirit",
        action_class: "button button_action",
        icon: "images/action_commandspirit.png",
        btn_desc: "<b>Command Spirit</b><br><br><i>Simple Action</i>",
        title: "Command Spirit",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Issuing a command to a single spirit or group of spirits under a summoner's control is a Simple Action.",

    },
    {
        action_id: "action_dismissspirit",
        action_class: "button button_action",
        icon: "images/action_dismissspirit.png",
        btn_desc: "<b>Dismiss Spirit</b><br><br><i>Simple Action</i>",
        title: "Dismiss Spirit",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "This is the action of freeing a spirit from the summoner's control. It does not immediately send the spirit back to its home plane but instead frees it to do as it chooses.",

    },
    {
        action_id: "action_firebow",
        action_class: "button button_action",
        icon: "images/action_firebow.png",
        btn_desc: "<b>Fire Bow</b><br><br><i>Simple Action</i>",
        title: "Fire Bow",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Firing a single arrow from a loaded bow is a Simple Action. To nock a single arrow, the character must use the Reload Weapon Simple Action.",

    },
    {
        action_id: "action_firegun",
        action_class: "button button_action",
        icon: "images/action_firegun.png",
        btn_desc: "<b>Fire Semi-Auto, <br>Single-Shot, Burst Fire or Full-Auto</b><br><br><i>Simple Action</i>",
        title: "Fire Semi-Auto, Single-Shot, Burst Fire or Full-Auto",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may fire a readied firearm in Semi-Automatic, Single-Shot, Burst-Fire, or Fully-Auto mode via a Simple Action (see Firearms, p. 424) but may not take any other attack actions in the same Action Phase. If a character has one weapon in each hand, he may fire once with each weapon by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 96); the off-hand modifier applies (see Attacking Using Off-Hand Weapon, p. 178). When taken as Simple Actions, Burst Fire fires 3 bullets, while Full-Auto fires 6 bullets.",

    },
    {
        action_id: "action_insertclip",
        action_class: "button button_action",
        icon: "images/action_insertclip.png",
        btn_desc: "<b>Insert Clip</b><br><br><i>Simple Action</i>",
        title: "Insert Clip",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may insert a fresh clip into a ready firearm by taking a Simple Action, but only if he has first removed the previous clip (see Remove Clip, p. 166, and Reloading Weapons, p. 163).",

    },
    {
        action_id: "action_observeindetail",
        action_class: "button button_action",
        icon: "images/action_observeindetail.png",
        btn_desc: "<b>Observe In Detail</b><br><br><i>Simple Action</i>",
        title: "Observe In Detail",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may make a detailed observation by taking a Simple Action. This allows a Perception Test (see Using Perception, p. 135). <br><br> Note that characters should always be able to observe what is immediately obvious (gamemaster's discretion, keeping in mind any perception enhancements the character may have) without having to spend a Simple Action and make a Perception Test. For example, a character might automatically be aware that someone is running toward him with something in hand; however, the gamemaster may decide that the character cannot tell if it is a friend or foe or what is in their hand without taking an Observe in Detail action.",

    },
    {
        action_id: "action_pickup",
        action_class: "button button_action",
        icon: "images/action_pickup.png",
        btn_desc: "<b>Pick Up/Put Down Object</b><br><br><i>Simple Action</i>",
        title: "Pick Up/Put Down Object",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may pick up an object within reach or put down one that he was holding as a Simple Action. This action means care is taken to put the object down or pick it up. Just dropping an object is a Free Action, but items that get dropped are more likely to be damaged than items that are set down.",

    },
    {
        action_id: "action_quickdraw",
        action_class: "button button_action",
        icon: "images/action_quickdraw.png",
        btn_desc: "<b>Quick Draw</b><br><br><i>Simple Action</i>",
        title: "Quick Draw",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may attempt to quick-draw a pistol, pistol-sized weapon, or small throwing weapon and immediately fire it by using a Quick Draw Simple Action. For the character to successfully draw the weapon, the player must make a (Weapon Skill) + Reaction [Physical] (3) Test. If the weapon is held in a quick-draw holster (see p. 432), reduce the threshold to 2. If the test is successful, the character draws the weapon and fires as a single Simple Action. If the test fails, he clears the gun but cannot fire with the same action. If he glitches, the gun is stuck in the holster or dropped, and no more actions are allowed. On a critical glitch, a drawn blade may be fumbled out of the character's reach or a pistol accidentally fired while still in the holster; the gamemaster decides the exact nature of the screw-up. <br><br> Only properly holstered weapons can be quick- drawn. They do not have to be in a quick-draw holster, but they do need to be in a holster or sheath or on a proper sling to be quick-drawn. Two weapons may be quick-drawn and fired simultaneously, but the (Weapon Skill) + Reaction dice pool is split, and off-hand penalties apply.",

    },
    {
        action_id: "action_readyweapon",
        action_class: "button button_action",
        icon: "images/action_readyweapon.png",
        btn_desc: "<b>Ready Weapon</b><br><br><i>Simple Action</i>",
        title: "Ready Weapon",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may ready a weapon by spending a Simple Action. The weapon may be a firearm, melee weapon, throwing weapon, ranged weapon, or mounted or vehicular weapon. Readying entails drawing a firearm from a holster, drawing a throwing or melee weapon from a sheath, picking up any kind of weapon, or generally preparing any kind of weapon for use. A weapon must be ready before it can be used. Weapons not held in a traditional holster may require a Complex Action to ready at the gamemaster's discretion.<br><br>A character can ready a number of small throwing weapons, such as throwing knives or shuriken, equal to one-half his Agility (round up) per Ready Weapon action.",

    },
    {
        action_id: "action_reckless",
        action_class: "button button_action",
        icon: "images/action_reckless.png",
        btn_desc: "<b>Reckless Spellcasting</b><br><br><i>Simple Action</i>",
        title: "Reckless Spellcasting",
        book_src: "Core Rulebook, p.165",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A spellcaster may use a Simple Action to cast a spell more quickly, but at the cost of higher Drain. See Step 4: Cast Spell, p. 281.",

    },
    {
        action_id: "action_removeclip",
        action_class: "button button_action",
        icon: "images/action_removeclip.png",
        btn_desc: "<b>Remove Clip</b><br><br><i>Simple Action</i>",
        title: "Remove Clip",
        book_src: "Core Rulebook, p.166",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may remove a clip from a ready firearm by taking a Simple Action (see Insert Clip, p. 165, and also Reload Weapons, p. 163). It takes another Simple Action to grab a fresh clip and slam it into the weapon.",

    },
    {
        action_id: "action_shiftperc",
        action_class: "button button_action",
        icon: "images/action_shiftperc.png",
        btn_desc: "<b>Shift Perception</b><br><br><i>Simple Action</i>",
        title: "Shift Perception",
        book_src: "Core Rulebook, p.166",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character capable of Astral Perception may shift perception to or from Astral Space as a Simple Action.",

    },
    {
        action_id: "action_standup",
        action_class: "button button_action",
        icon: "images/action_standup.png",
        btn_desc: "<b>Stand Up</b><br><br><i>Simple Action</i>",
        title: "Stand Up",
        book_src: "Core Rulebook, p.166",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "Using a Simple Action, a character who is lying down or prone may stand up. If the character is wounded and attempting to stand, he must succeed in a Body + Willpower (2) Test to do so (wound modifiers apply to this test).",

    },
    {
        action_id: "action_takeaim",
        action_class: "button button_action",
        icon: "images/action_takeaim.png",
        btn_desc: "<b>Take Aim</b><br><br><i>Simple Action</i>",
        title: "Take Aim",
        book_src: "Core Rulebook, p.166",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may take aim with a ready firearm, bow, or throwing weapon as a Simple Action. Take Aim actions are cumulative, but the benefits are lost if the character takes any other kind of action—including a Free Action — at any time before attacking. Take Aim actions may be extended over multiple Action Phases and Combat Turns. The maximum bonus a character may gain from sequential Take Aim actions, either to her limit or her dice pool, is equal to one-half the character's Willpower, rounded up.<br><br>Each Take Aim action applies a +1 dice pool modifier or +1 Accuracy increase to the Attack Test.<br><br>If the character is using image magnification or a targeting scope, Take Aim must be used to line up the shot in order to receive the bonus from the item. In this case the first action of Take Aim does not provide any additional bonus beyond enabling the function of the modification.",

    },
    {
        action_id: "action_takecover",
        action_class: "button button_action",
        icon: "images/action_takecover.png",
        btn_desc: "<b>Take Cover</b><br><br><i>Simple Action</i>",
        title: "Take Cover",
        book_src: "Core Rulebook, p.166",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may use this Simple Action to gain a cover bonus to their defense test, as long as she is not surprised (see Surprise, p. 192). A character who is surprised may not take cover.",

    },
    {
        action_id: "action_throwweapon",
        action_class: "button button_action",
        icon: "images/action_throwweapon.png",
        btn_desc: "<b>Throw Weapon</b><br><br><i>Simple Action</i>",
        title: "Throw Weapon",
        book_src: "Core Rulebook, p.166",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character may throw a ready throwing weapon (see Ready Weapon, p. 165) by taking a Simple Action. The character may not take any other attack actions in the same Action Phase. Multiple readied throwing weapons can be thrown at a target within Short or Medium range by adding a Multiple Attacks Free Action (see Multiple Attacks, p. 196).",

    },
    {
        action_id: "action_usesimpledevice",
        action_class: "button button_action",
        icon: "images/action_usesimpledevice.png",
        btn_desc: "<b>Use Simple Device</b><br><br><i>Simple Action</i></i>",
        title: "Use Simple Device",
        book_src: "Core Rulebook, p.166",
        action_type: "<i>Simple Action</i>",
        action_detail1: "",
        action_detail2: "",
        description: "A character can use any simple device with a Simple Action. Simple devices are those that are activated with a simple movement like a thumb trigger, pressing a single key, or tapping a single icon.",

    },
    {
        action_id: "matrix_calldissprite",
        action_class: "button button_resonance",
        icon: "images/matrix_calldissprite.png",
        btn_desc: "<b>Call/Dismiss Sprite</b><br><br><i>Simple Action</i><br><i><u>Resonance Action</u></i>",
        title: "Call/Dismiss Sprite",
        book_src: "Core Rulebook, p.250",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Resonance Action</i></u>",
        action_detail2: "<b>Test:</b> n/a</p>",
        description: "You call a registered sprite you have waiting in the Resonance, which appears at the beginning of the next Combat Turn. You can also use this action to send a sprite back to the Resonance, releasing it from any tasks it still owes you, which it does on its next action.",

    },
    {
        action_id: "matrix_changeicon",
        action_class: "button button_matrix",
        icon: "images/matrix_changeicon.png",
        btn_desc: "<b>Change Icon</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Change Icon",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> none <br> <b>Test:</b> none (Data Processing action)",
        description: "You change the target's icon to one that you have a copy of or have designed yourself. Changing an icon doesn't change the results of a Matrix Perception action, but might fool personas who don't take the time to inspect your new look. You can target your own icon, if you like.",

    },
    {
        action_id: "matrix_cos",
        action_class: "button button_matrix",
        icon: "images/matrix_cos.png",
        btn_desc: "<b>Check Overwatch Score</b><br><br><i><i>Simple Action</i><br><u>Matrix Action</u></i>",
        title: "Check Overwatch Score",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> none <br> <b>Test:</b> Electronic Warfare + Logic [Sleaze] v. 6 dice",
        description: "You find out how close the grid is to converging on you. Checking the OS is a Sleaze action, so the defense against it will add to your OS. If you succeed, the gamemaster tells you what your OS was when you started the action, then adds the hits from the defending dice pool.",

    },
    {
        action_id: "matrix_commandsprite",
        action_class: "button button_resonance",
        icon: "images/matrix_commandsprite.png",
        btn_desc: "<b>Command Sprite</b><br><br><i>Simple Action</i><br><i><u>Resonance Action</u></i>",
        title: "Command Sprite",
        book_src: "Core Rulebook, p.250",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Resonance Action</i></u>",
        action_detail2: "<b>Test:</b> n/a</p>",
        description: "You command a sprite to do something for you, using up one of its tasks.",

    },
    {
        action_id: "matrix_controldevice",
        action_class: "button button_matrix", 
        icon: "images/matrix_controldevice2.png",
        btn_desc: "<b>Control Device (2 marks)</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Control Device",
        book_src: "Core Rulebook, p.238",
        action_type: "<i>Variable Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> varies <br> <b>Test:</b>  (as action) [Data Processing (or special)] v. (as action) or Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall",
        description: "You perform an action through a device you control(or at least control sufficiently), using your commlink or deck like a remote control or video-game controller. The dice pool of any test you make using this action uses the rating of the appropriate skill and attribute you would use if you were performing the action normally. For example, firing a drone-mounted weapon at a target requires a Gunnery + Agility test, and using a remote underwater welder calls for a Nautical Mechanic + Logic test. All actions you take while controlling a device use either the normal limit for that action or your Data Processing rating, whichever is lower. If there is no test associated with the action you want the device to perform (such as unlocking a maglock or ejecting a clip from a pistol), you must succeed in an Electronic Warfare + Intuition [Sleaze] v. Intuition + Firewall test to perform the action. <br><br> You can use this action to control multiple devices at once. If you are the owner of all devices being commanded and they are all being commanded to do exactly the same thing, taking this action costs nothing extra. Otherwise, you must split your dice pool into a number of groups equal to the number of devices you want to control with a single action. <br><br> The type of action this is (i.e., Free, Simple, Standard, and Complex) is the same as the type of action attempted with the device, and it requires 1 mark for Free Actions, 2 marks for Simple Actions, and 3 marks for Standard or Complex Actions. <br><br> This action is a Sleaze action whenever you use your Sleaze as a limit in the test, which incurs the same risk of Overwatch Score and consequences of failure as all Sleaze actions."
    },
    {
        action_id: "matrix_jackout",
        action_class: "button button_matrix",
        icon: "images/matrix_jackout.png",
        btn_desc: "<b>Jack Out</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Jack Out",
        book_src: "Core Rulebook, p.240",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> Owner <br> <b>Test:</b> Hardware + Willpower [Firewall] v. Logic + Attack",
        description: "This jacks you out of the Matrix and reboots the device you are using. You suffer dumpshock if you were in VR. The defense pool only applies if you've been link-locked (p. 229) by someone; the test is against the icon that locked your link. If more than one persona has you link-locked, you need to beat each of them individually: use a single roll and compare your hits to rolls from each opponent who had established a link-lock.<br><br>You can only jack out yourself. You can't dump other people except by beating them into submission through Matrix damage.",

    },
    {
        action_id: "matrix_invitemark",
        action_class: "button button_matrix",
        icon: "images/matrix_invitemark.png",
        btn_desc: "<b>Invite Mark</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Invite Mark",
        book_src: "Core Rulebook, p.240",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> Owner <br> <b>Test:</b> none (Data Processing action)",
        description: "If you're the owner of a device, file, persona, host, or IC program, you can offer other icons the opportunity to put a mark on your device, file, etc. When you make the offer, you choose the number of marks allowed, their duration, and how long the offer stands. The invitee can then mark your icon with a Free Action. You may revoke your offer at any time before the mark is placed, but once another icon has a mark, you need to either use the Erase Mark action or reboot your device to remove it before the duration you chose expires.",

    },
    {
        action_id: "matrix_sendmessage",
        action_class: "button button_matrix",
        icon: "images/matrix_sendmessage.png",
        btn_desc: "<b>Send Message</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Send Message",
        book_src: "Core Rulebook, p.242",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> n/a (or 1) <br> <b>Test:</b> none (Data Processing action)",
        description: "You send a text or audio message the length of a short sentence, an image, or a file via the Matrix to a user whose commcode you have. If you're using the Matrix through a DNI, even if you're in AR, you can send longer and more complicated messages, about a paragraph worth of text. You can also use this action to open a live feed to one or more recipients, using any digital recording devices you have.",

    },
    {
        action_id: "matrix_sim",
        action_class: "button button_matrix",
        icon: "images/matrix_sim.png",
        btn_desc: "<b>Switch Interface Mode</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Switch Interface Mode",
        book_src: "Core Rulebook, p.243",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> Owner <br> <b>Test:</b> none (Data Processing action)",
        description: "You switch your perception from AR to VR or vice versa. Switching to VR causes your body to go limp, so don't do it somewhere dangerous. If you switch from VR to AR, you lose the bonus Initiative Dice from VR (Changing Initiative, p. 160). If you're link-locked (p. 229), you cannot switch interface modes.<br><br>You can only do this to yourself; you can't switch other people's interface mode.",

    },
    {
        action_id: "action_clinch",
        action_class: "button button_martial",
        icon: "images/action_clinch.png",
        btn_desc: "<b>Clinch</b><br><br><i>Simple Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Clinch",
        book_src: "Run & Gun, p.119",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Use of this action requires Martial Art training.</i></u>",
        action_detail2: "",
        description: "A Clinch is a grappling position in a stand-up fight, where the opponent's effective Reach has been neu- tralized. A Clinch is included in several martial arts and can be used as a medium to move from a stand-up fight to a ground fight through throws and knock down actions. With a successful opposed Gymnastics + Agility [Physical] vs. Reaction + Intuition Test, the character has clinched their opponent. This means that the character has a hold of the opponent (and possibly visa versa), so they can't move away from each other. The difference between a Clinch and a Grapple action is that a Grapple involves a lock or choke hold on the opponent to immobilize him, while a Clinch doesn't immobilize an opponent and allows both the character and opponent to make actions other than those involving the Clinch.<br><br>The character who initiated the Clinch gets the Superior Position bonus modifier to actions while maintaining control of the Clinch. Both the character and opponent's Reach bonus are negated, and attacks with melee weapons receive a penalty equal to their Reach bonus. Firearm use by both the character and opponent are penalized by the net successes of the Clinch. Unless the opponent escapes from the Clinch, neither opponent nor character can move away from each other. They can, however, move up to 2 meters on each of their actions together. A character in the inferior position can attempt to use an Escape Action (see below) to break the Clinch. A character in the Superior Position can let go of the Clinch as a Free Action; at this point the character in an inferior position can choose to use an Interrupt Action (–5 Initiative Score) to attempt to maintain the Clinch and gain Superior Position. This requires a new Gymnastics + Agility [Physical] by the player in the inferior position, and they receive a +1 dice pool bonus thanks to the fact that they are already in contact with the other character; the character in the Superior Position does not get the Superior Position bonus in this instance.<br><br>A successful Clinch Action can lead to a Subdual, Called Shot: Knockdown, or Throw.",

    },
    {
        action_id: "action_iaijutsu",
        action_class: "button button_martial",
        icon: "images/action_iaijutsu.png",
        btn_desc: "<b>Iaijutsu</b><br><br><i>Simple Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Iaijutsu",
        book_src: "Run & Gun, p.122",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Use of this action requires Martial Art training.</i></u>",
        action_detail2: "",
        description: "Iaijutsu is the art of sword drawing, though this technique goes beyond just using a sword. With this action, the character may perform Quick Draw Simple Action (p. 165, SR5) with any melee weapon. As with the quick draw rules, the weapon must be properly sheathed or holstered in order to use the Quick Draw Action. If successful, the character can then attack with the weapon as a Simple Action instead of a Complex Action for that Action Phase. ",

    },
    {
        action_id: "action_kipup",
        action_class: "button button_martial",
        icon: "images/action_kipup.png",
        btn_desc: "<b>Kip-Up</b><br><br><i>Simple Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Kip-Up",
        book_src: "Run & Gun, p.122",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<i><u>Unarmed Combat Only</u></i>",
        action_detail2: "<u><i>Use of this action requires Martial Art training.</i></u>",
        description: "From a Prone position, the character can kick himself back into a standing position and perform an immediate Close Combat Attack Action against a nearby target. The character must make an Agility + Gymnastics [Phys- ical] (3) Test. If successful, the character can then make a Close Combat Attack as a Simple Action. The character can't move from a Kip-up to attack an opponent if they are not in Reach. Failure on a Kip-up Action means that the character is still Prone.",

    },
    {
        action_id: "action_push",
        action_class: "button button_action",
        icon: "images/action_push.png",
        btn_desc: "<b>Push</b><br><br><i>Simple Action</i>",
        title: "Push",
        book_src: "Run & Gun, p.123",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<i><u>Unarmed Combat Only</u></i>",
        action_detail2: "",
        description: "The character can make an Unarmed Combat Attack Test against an opponent within the character's Reach. If successful, the opponent is pushed outside the Reach of the character, a minimum of 1 meter. No damage is done with the attack. The character can move up to their Walk rate, and the location of where the opponent is pushed is determined by the person giving the push. This can be done as an Intercept Action (–5 Initiative Score) if an opponent attempts to move into the character's Reach space. The pushing character cannot be in a Grapple or Clinch.",

    },
    {
        action_id: "action_shove",
        action_class: "button button_action",
        icon: "images/action_shove.png",
        btn_desc: "<b>Shove</b><br><br><i>Simple Action</i>",
        title: "Shove",
        book_src: "Run & Gun, p.123",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<i><u>Unarmed Combat Only</u></i>",
        action_detail2: "",
        description: "While the character is running, the character can make an Unarmed Combat Attack Test against an opponent with the intent of moving him from his location. Like a Charge, the character has to Run at the opponent and make an Unarmed Combat Attack Test. The attack deals no damage. If successful and the character's Strength + net hits exceeds the opponent's Physical Limit, the opponent is pushed back a distance in meters equal to the net hits of the Attack Test in the direction of the attacking character's movement. If successful and the character's Strength + net hits does not exceed the opponent's Physical Limit, the character has met Mr. Wall and thus does not move the opponent; they cannot move any further past the opponent in this phase. If unsuccessful, the character falls Prone, tripping up before the attempt or knocked back from the impact against the opponent. The gamemaster determines the exact location where the character ends up.",

    },
    {
        action_id: "action_throwperson",
        action_class: "button button_martial",
        icon: "images/action_throwperson.png",
        btn_desc: "<b>Throw Person</b><br><br><i>Simple Action</i><br><i><u>Martial Art Required</u></i>",
        title: "Throw Person",
        book_src: "Run & Gun, p.123",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Use of this action requires Martial Art training.</i></u>",
        action_detail2: "",
        description: "If the character has successfully engaged in a Clinch or Subduing action against an opponent, he may then attempt to throw their opponent. Throw person can also be done as an Interrupt Action (–10 from Initiative Score) after successfully blocking an opponent's attack. A throw is done using the leverage of the opponent's body and/or force of action into projecting the opponent to the ground. The character rolls an Unarmed Combat Attack Test, opposed as normal. If the charac-ter succeeds and character's Strength + net hits exceed the opponent's Physical Limit, the opponent can then be thrown up to a number of meters equal to the net hits scored on the test. The maximum distance that a character can throw an opponent is the difference in the char- acter's Strength minus the opponent's Body in meters. If this distance value is less than 0, then the maximum distance is 0, meaning less than one meter away from the character. The opponent suffers damage equal to the net successes of the test, not the distance thrown. At the end of the throw, the opponent is Prone. The opponent could suffer additional damage at the location where he is thrown, such as a fire pit or into the mouth of a sarlacc. If the character is successful in the attack but does not exceed the opponent's Physical Limit, the opponent is not thrown and is still standing but remains in a Clinch or Subduing grip. Failure means the target is not thrown and also escapes the character's grip."
    },
    {
        action_id: "matrix_btl",
        action_class: "button button_matrix",
        icon: "images/matrix_btl.png",
        btn_desc: "<b>Break Target Lock</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Break Target Lock",
        book_src: "Rigger 5.0, p.30",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Electronic Warfare + Intuition [Data Processing] v. Logic + Sensors",
        description: "Passive targeting and active targeting with sensors are described on p. 184 of SR5. If you know that you've been locked (or suspect it), you can to try to break it. Choose an enemy that has (or you think has) a lock on you, and make the Opposed Test. For every net hit, you reduce the target's lock on you by one hit. Your RCC's Noise Reduction rating is added as a dice pool bonus for this action.",

    },
    {
        action_id: "matrix_calibration",
        action_class: "button button_matrix",
        icon: "images/matrix_calibration.png",
        btn_desc: "<b>Calibration</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Calibration",
        book_src: "Kill Code p.37",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> One per persona <br> <b>Test:</b> Electronic Warfare + Logic [Data Processing]",
        description: "<i>Lending your team your own processing power, you boost their speed.</i><br><br> You can increase the current Initiative Score of a number of personas on whom you have marks by 1 for every 2 hits. The number of personas affected cannot exceed your Data Processing. The Initiative Score then decreases each Combat Turn as normal.",

    },
    {
        action_id: "matrix_dos",
        action_class: "button button_matrix",
        icon: "images/matrix_dos.png",
        btn_desc: "<b>Denial of Service</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Denial of Service",
        book_src: "Kill Code p.37",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> See description <br> <b>Test:</b> Cybercombat + Logic [Attack] v. Willpower + Firewall",
        description: "<i>Wireless enemy weapons become nearly unusable when you pollute their data streams with noise.</i><br><br>A decker or technomancer may target a wirelessly active device or PAN. Make a Computer + Intuition [Data processing] Test opposed by Willpower + Firewall, and apply the number of net hits x 2 as a negative dice pool modifier to all tests made with that device until the beginning of the next Combat Turn. For every mark the decker or technomancer has on an enemy PAN, they may apply this effect to two additional devices slaved to the PAN.",

    },
    {
        action_id: "matrix_popup",
        action_class: "button button_matrix",
        icon: "images/matrix_popup.png",
        btn_desc: "<b>Popup</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Popup",
        book_src: "Kill Code p.39",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> 1 <br> <b>Test:</b> Hacking + Logic [Sleaze] or Cybercombat + Logic [Attack] v. Willpower + Firewall",
        description: "<i>Honey, I swear I never visit those sites. Where are all these coming from? I don't know why this is happening …</i><br><br>Target must be a persona not running in VR. If the target has wireless-enabled AR, they are flooded with Matrix spam, taking a penalty to all actions equal to [net hits] until the start of the attacker's next Combat Turn. If the attacker uses Cybercombat + Logic, the attack also deals Matrix damage equal to net hits. If the attacker uses Hacking + Logic, they may immediately act as if the net hits on the attack were net hits on a Matrix Perception test, and they gain any relevant information.",

    },
    {
        action_id: "matrix_squelch",
        action_class: "button button_matrix",
        icon: "images/matrix_squelch.png",
        btn_desc: "<b>Squelch</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Squelch",
        book_src: "Kill Code p.39",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Electronic Warfare + Logic [Attack] v. Sleaze + Intuition",
        description: "<i>Why won't my comm work? And what is that noise?</i><br><br>A successful Squelch test prevents the target device from calling or sending messages for a number of minutes equal to the net hits scored.",

    },
    {
        action_id: "matrix_tag",
        action_class: "button button_matrix",
        icon: "images/matrix_tag.png",
        btn_desc: "<b>Tag</b><br><br><i>Simple Action</i><br><i><u>Matrix Action</u></i>",
        title: "Tag",
        book_src: "Kill Code p.40",
        action_type: "<i>Simple Action</i>",
        action_detail1: "<u><i>Matrix Action</i></u>",
        action_detail2: "<b>Marks Required:</b> None <br> <b>Test:</b> Computer + Logic [Data Processing] v. Sleaze + Intuition",
        description: "<i>You track and analyze enemy movements in real time, giving your allies the edge in engagement.</i><br><br>The hacker may “tag” a number of targets on a single PAN, equal to their net hits, within their line of sight. They can then relay those tags wirelessly to allies. Tagging a target negates up to 2 dice in penalties from Visibility and Light/Glare to any affected ranged attack rolls allies may be making against that target, including blind-fire due to invisibility or shooting through cover. Allies who can see a tag may also take one additional Take Aim Action against that target as a Free Action on each Initiative Pass.<br><br>Tags may be sustained by spending a Simple Action to refresh the tags each Combat Turn. When using a PI-Tac, the hacker may add the PI-Tac's level to the number of targets they may tag. Note: In order for allies to receive this bonus, they must have the ability to see AROs.",

    }
]